### ISSUE TITLE
Integração WooCommerce Product Vendors

### ISSUE THREAD

**Issue by mayracarvalho** [claudiosanches/woocommerce-correios#103]
Olá Claudio, tudo bem?

Tenho o meu site no WooCommerce e como quero migrar as marcas para o sistema de market place (vendedores). Baixei o plugin WooCommerce Product Vendors e pelo o que vi, aparentemente não tem integração com os correios, confere?!

Eu precisaria do plugin principalmente para o frente, por exemplo: o cliente compra de uma marca/vendedor do Amapá, e outra de São Paulo, precisaria somar esses 2 ceps e computador no valor final da compra. Já testei fazendo um pedido de um cep de Rondônia, e outro produto com cep de São Paulo, e não somou.

Será que funciona? Estou tendo dificuldade para colocar entrega personalizada para cada vendedor e depois somar no carrinho com produtos de outros vendedores.

Obrigada,
Bjs

**Comment by edmarholanda** [comment]
Neste site https://art-idesenvolvimento.com.br eles vendem um plugin que faz este tipo de integração. O plugin funciona com Dokan, WC Vendors e WCMarketplace: 

Eu comprei para implementar no meu WC Vendors, mas estou tão ocupado noutro projeto que ainda não consegui testá-lo adequadamente.

**Comment by claudiosanches** [comment]
Fechando porque o plugin já tem filtros para aceitar CEPs diferentes.
