### ISSUE TITLE
Campo de usuário e senha para os contratos dos Correios

### ISSUE THREAD

**Issue by RaphaelBatagini** [claudiosanches/woocommerce-correios#105]
Claudio, acha válido o plugin apresentar na administração campos para armazenar usuário e senha de contrato com os Correios?
Hoje o tracking history dos correios só está trazendo uma linha do registro para mim (a primeira pra piorar). Li sobre uma galera que teve este problema e resolveu adicionando os dados de contrato.
Estou pensando em fazer um pull request com esta melhoria, o que acha? Usar o que o usuário preencheu como primeira opção e o usuário e senha padrão como fallback.

**Comment by claudiosanches** [comment]
Seria uma boa adicionar essa opção.
