### ISSUE TITLE
Campo de Estado não atualiza no autofill-address quanto o Select2 é utilizado

### ISSUE THREAD

**Issue by vinigarcia87** [claudiosanches/woocommerce-correios#106]
Ao utilizar o plugin Select2 (https://select2.org/) para as dropdowns do sistema, o Autofill do WC Correios não consegue atualizar corretamente a dropdown de Estado.

O suporte pode ser incluido, adicionando a seguinte linha de codigo, no arquivo autofill-address.js, linha 129:

`$( '#' + field + '_state' ).val( data.state ).trigger('change'); // Select2 support`

**Comment by claudiosanches** [comment]
Acabei de testar com o WooCommerce 3.5.5 e funciona sem nenhum problema com o código atual.

**Comment by allysonsouza** [comment]
Utilizando o WooCommerce 3.4.5 não estava funcionando mesmo, obrigado pelo código @vinigarcia87
