### ISSUE TITLE
Tabela de Histórico de Pedidos

### ISSUE THREAD

**Issue by guilhermekf** [claudiosanches/woocommerce-correios#109]
Estou tendo algum problema para conseguir mostrar a tabela de histórico corretamente. 

Não tenho certeza se o erro é do plugin ou do webservice dos correios:

Tabela na pagina do pedido:
![image](https://user-images.githubusercontent.com/8038504/39397621-d09fc3aa-4ad8-11e8-9577-e50e8652084c.png)

Site do correio:
![image](https://user-images.githubusercontent.com/8038504/39397623-e2d532d0-4ad8-11e8-9e1d-28a79b7ce4b9.png)

Log da integração:
![image](https://user-images.githubusercontent.com/8038504/39397627-f1fefc46-4ad8-11e8-9ee8-36e869cdb64d.png)

Obrigado

**Comment by claudiosanches** [comment]
Aparecendo apenas o último resultado... Parece que os Correios agora estão apenas mostrando última atualização no lugar de todo o histórico, para ver tudo precisa de contrato com os Correios.
Acabei de adicionar opções para isso no plugin e devo lançar uma versão em breve.
