### ISSUE TITLE
Coloquem o CEP no carrinho ou na página de produto, por favor.

### ISSUE THREAD

**Issue by BernardoLima** [claudiosanches/woocommerce-correios#110]
Não fica usual só saber o preço do frete no final, muitos clientes não compram por causa da falta da informação ou do trabalho necessário para ter a informação do frete só no final, por favor, considerem colocar a informação também no carrinho e/ou na página de produto.

**Comment by claudiosanches** [comment]
Não faz parte do escopo deste plugin controlar onde a calculadora de frete deve aparecer, este plugin faz apenas integração com os Correios e de forma alguma se destina a controlar todo o sistema de entregas do WooCommerce.
Se você quer uma calculadora de frete no carrinho, deve procurar por um plugin para isso, em breve devo estar lançando um plugin novo com esta finalidade.
