### ISSUE TITLE
avisar de breaking changes

### ISSUE THREAD

**Issue by luizbills** [claudiosanches/woocommerce-correios#112]
Recomendo começar a usar [semver](https://semver.org/) como estilo das versões para esse plugin e se possível até para os seus outros. 

Alguma atualização recente começou a mostrar a entrega estimada no *meta* ao invés de ser no *label*. E isso quebra várias soluções que costumavam alterar o *label* do método de entrega (adicionar o texto "Frete Grátis" é bem comum, por exemplo).

E como no changelog não dava muitas informações tive que sair lendo o código até perceber essa mudança. Aliás, a função `wc_correios_get_estimating_delivery` nem foi marcada como obsoleta.

Enfim... Usando semver, vai alertar desenvolvedores quando virem um *MAJOR release*.

**Comment by claudiosanches** [comment]
É usado semver, no caso não teve qualquer tipo de mudança que quebrou os métodos "legacy", essa função também não esta obsoleta, apenas não é usada mais nos mesmos lugares.
Por isso não foi alterado para uma versão MAJOR, até porque o método antes de apresentar informação de estimativa de entrega era um hack.
