### ISSUE TITLE
Nomenclatura de métodos "delivery forecast".

### ISSUE THREAD

**Issue by luiseduardobraschi** [claudiosanches/woocommerce-correios#113]
"Delivery forecast" pelo que eu sei é o prazo de entrega (término de manufatura) de um produto numa produção.
O correto não seria "delivery estimate"?

**Comment by claudiosanches** [comment]
Isso veio em um Pull Request como contribuição #98
De qualquer forma "Estimate" parece correto, se quiser enviar um Pull Request para corrigir isso eu agradeço.
