### ISSUE TITLE
Contrato com correios e diferente taxas de entrega

### ISSUE THREAD

**Issue by maaxxicarvalho** [claudiosanches/woocommerce-correios#118]
Olá, gostaria de saber se o plugin oferece alguma forma de integração com os correios para clientes com contrato. O meu cliente tem um contrato com os correios que garante melhores taxas de entrega, gostaria de saber se é possivel trabalhar com esse tipo de contrato e buscar as diferentes taxas de entrega com o seu plugin.

Obrigado.

**Comment by henriquemattos** [comment]
Entendo que sim, @maaxxicarvalho . Você pode inserir o código do serviço e o tipo de serviço (corporativo ou convencional) na página de administração do tipo de entrega.

Crie uma área de entrega, insira o método de entrega (Sedex, Sedex 12, PAC, etc) e em cada opção você pode gerenciar o código e tipo do serviço. 

Veja se é isto que procura.
Abraços,
Henrique Mattos

**Comment by Chicodarave** [comment]
@maaxxicarvalho, sim amigo, eu uso, funciona 100% e não tem segredo nenhum para configurar.

**Comment by maaxxicarvalho** [comment]
Obrigado @henriquemattos e @Chicodarave 
Funcionou perfeitamente!
