### ISSUE TITLE
Método de envio na impressão do pedido

### ISSUE THREAD

**Issue by Chicodarave** [claudiosanches/woocommerce-correios#119]
Prezado Claudio, uso o plugin "WooCommerce PDF Invoices & Packing Slips" para impressão dos pedido, eu criei um template para ele apresentar os dados da maneira que eu precisava (é em PHP).
O método de envio eu estava pegando da seguinte maneira: $this->order->get_shipping_method();
Ele apresentava algo como "PAC (prazo de X dias úteis)"
Aqui vem a primeira questão, eu sempre quis que mostrasse somente PAC ou Sedex, você sabe me dizer como faço isso?
A segunda questão é a seguinte:
Depois de atualizar ele passou a mostrar "PAC (entrega dentro de X dias úteis, após o pagamento)" e fica estranho isso escrito na etiqueta.
Tem como alterar isso para "... X dias após a postagem" por exemplo?
De qualquer forma, na etiqueta em si eu gostaria que fosse somente o nome do método mesmo.

Muito obrigado.
Seu plugin é show!

**Comment by Chicodarave** [comment]
Claudio, tenho uma outra sugestão.
Seria possível criar uma nova coluna do método de envio para ficar na lista dos pedidos?
Assim poderia organizar as encomendas pela forma de envio.

**Comment by claudiosanches** [comment]
Já resolvido nas versões atuais do plugin.
