### ISSUE TITLE
Frete Gratis para CEP SC

### ISSUE THREAD

**Issue by murilomf** [claudiosanches/woocommerce-correios#120]
Boa Noite,

Segui o passo a passo para configurar o Frete Gratis para CEPs da minha regiao, no caso, Grande Florianópolis, e não aparece no checkout.
Alguém já teve o mesmo problema ?

**Comment by claudiosanches** [comment]
Consegue criar frete gratis usando áreas de entrega e os métodos de entrega do WooCommerce, não precisa fazer nada relacionado com este plugin.
