### ISSUE TITLE
Alterar CEP não atualiza endereço

### ISSUE THREAD

**Issue by Chicodarave** [claudiosanches/woocommerce-correios#121]
Prezado, na tela de finalizar pedido, quando se altera o CEP o sistema não está atualizando o endereço pelo novo CEP se o campo "Endereço" já estiver preenchido, ficará o novo CEP com o endereço antigo.
Fica de sugestão, ao atualizar o CEP ele atualizar o endereço pelo novo CEP.

Obrigado.

**Comment by claudiosanches** [comment]
Meu querido prezado, tem opção para isso na configuração de integração do plugin, ativando ele vai sempre forçar para atualizar todo o endereço do cliente, existe opção para não forçar, caso o cliente coloque CEP incorreto e troque todo o endereço, ambas as opções existem por causa de pedido de usuários.

**Comment by claudiosanches** [comment]
Aqui a opção:
![test](https://user-images.githubusercontent.com/1264099/43863522-5984fabe-9b33-11e8-9398-66dcaf59aa73.png)

**Comment by Chicodarave** [comment]
Perfeito! Muito obrigado!

**Comment by Chicodarave** [comment]
Claudio, posso dar uma sugestão?
Quando CEP é alterado o sistema pergunta se o comprador quer atualizar o endereço pelo novo CEP.

Um abraço.
