### ISSUE TITLE
Problemas com as tabelas de frete sumindo

### ISSUE THREAD

**Issue by zeinnicholas** [claudiosanches/woocommerce-correios#122]
Claudio,

faz um tempo já, tenho encontrado problemas na funcionalidade do plugin. A tabela de frete some e fica impossível finalizar a compra. O WooCommerce avisa que não há métodos de entrega disponíveis. Tentei de tudo, inclusive trocar de tema e deixar só os plugins básicos:

- WooCommerce
- WooCommerce Correios
- Extra Checkout Fields

Não adiantou. 

Tem um tópico no fórum do Wordpress falando sobre o problema. Você poderia me dar uma luz?
[https://wordpress.org/support/topic/tabela-do-frete-nao-aparece-na-pagina-do-carrinho-nem-na-pagina-checkout/#post-10603365](url)

Obrigado.

**Comment by claudiosanches** [comment]
Já foi corrigido nas versões atuais do plugin.
