### ISSUE TITLE
Rastreio no pedido não funcionando ao clicar para consultar no site dos correios

### ISSUE THREAD

**Issue by rickslayer** [claudiosanches/woocommerce-correios#124]
Após o pedido concluído , aparece o rastreio numa seção chamada correios. Antes ao clicar no rastreio levava para o site do correios já com o rastreio inserido e o status.
Agora aparece a seguinte URL https://www2.correios.com.br/sistemas/rastreamento/resultado_semcontent.cfm
E no console do navegador aparece o seguinte endereço 
https://apmperformance.correios.com.br/jsi/riverbed_appinternals.d.ajax.js 0 

Alguém por acaso tem passado por isso?

**Comment by rafawhs** [comment]
Sim, a url é redirecionada para **https** no site dos correios, por isso esse erro. Tem um PR para contornar esse problema:
https://github.com/claudiosanches/woocommerce-correios/pull/123

**Comment by vivithchan** [comment]
fiz as modificações conforme os arquivos indicados e continuo com o mesmo problema.

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
