### ISSUE TITLE
API REST método para informar código de rastreio e já enviar por email os dados

### ISSUE THREAD

**Issue by AngosStudio** [claudiosanches/woocommerce-correios#125]
Olá, dei uma boa procurada aqui antes de criar a Issue, mas existe algum método de via API informar o código de rastreio e ele enviar o e-mail para o cliente? Se sim, poderia dizer como? Existe alguma documentação do que foi integrado da API (ou foi apenas incluído o código de rastreio no order mesmo?)? Desde já obrigado e parabéns pelo plugin, poupou um tempão de desenvolvimento aqui. Abrass

**Comment by claudiosanches** [comment]
Isso é adicionado já a API de pedidos do WooCommerce.
