### ISSUE TITLE
Consulta não está mais disponível, utilizar novo componente "Precificação REST Internacional"

### ISSUE THREAD

**Issue by DevMoustache** [claudiosanches/woocommerce-correios#126]
Boa tarde!

Na consulta de CEP Internacional, nenhuma forma de entrega é exibida, e os logs do plugin acusam um erro indicando que a URL solicitada para consulta não existe mais:

![image](https://user-images.githubusercontent.com/42074515/45718867-e35e2b00-bb74-11e8-82b1-c21b128f7833.png)

Ficamos no aguardo da correção, abs!

**Comment by mkraulich** [comment]
Verifiquei o mesmo problema, vou ver se consigo achar uma solução.

**Comment by wubuyun** [comment]
https://github.com/claudiosanches/woocommerce-correios/issues/133#issue-375205691

**Comment by ericlucasfr** [comment]
Ola, como podemos obter uma solução para reste problema, por favor ?
Muito obrigado...

**Comment by marcelowu** [comment]
Por enquanto uso esse para quebra o galho
https://apps2.correios.com.br/efi/app/simulaPrecoPrazoInternacional/index.php

![Capturar](https://user-images.githubusercontent.com/30912144/74180394-2dd6c080-4c1e-11ea-877e-3250ebdbe085.PNG)

**Comment by milazangirolame** [comment]
> Por enquanto uso esse para quebra o galho
> https://apps2.correios.com.br/efi/app/simulaPrecoPrazoInternacional/index.php
> 
> ![Capturar](https://user-images.githubusercontent.com/30912144/74180394-2dd6c080-4c1e-11ea-877e-3250ebdbe085.PNG)

marcelo, vc faz uma requisição post neste url https://apps2.correios.com.br/efi/api/v1/volumes/restricao/  ? 

fiz um teste agora e enviei os dados em json e me retornou a resposta 
`no matches found: [alturaObjeto:1.6,alturaObjeto:],util:servicosDisponiveis:[]}]`

pode enviar um exemplo de como vc monta a requisição?

**Comment by marcelowu** [comment]
[Cadastrar no id correios](https://apps.correios.com.br/componentes/home/index.html#/ajuda)
[curl](curl -X GET --header 'Accept: text/html' 'https://cws2.correios.com.br/precoprazoservice/rs/v1/internacional/preco-prazo/45110?cepOrigem=70902000&sgPaisDestino=US&coCidadeDestino=00187637&psObjeto=300&tpObjeto=1&servicosAdicionais=030&vlDeclarado=200.00')
[URL requisição](https://cws2.correios.com.br/precoprazoservice/rs/v1/internacional/preco-prazo/45110?cepOrigem=70902000&sgPaisDestino=US&coCidadeDestino=00187637&psObjeto=300&tpObjeto=1&servicosAdicionais=030&vlDeclarado=200.00)

**Comment by milazangirolame** [comment]
> ah, ok! roger that, valeu marcelo :)

**Comment by denisgomesfranco** [comment]
Alguma atualização sobre esse problema no plugin? O plugin não é atualizado há 5 meses, estou com 2 clientes precisando de frete internacional e não tenho solução no momento (não sou um programador tão top assim também rs)

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
