### ISSUE TITLE
Cálculo pela quantidade de itens

### ISSUE THREAD

**Issue by sebrax** [claudiosanches/woocommerce-correios#127]
Olá!

Integrei o plugin com o WC Marketplace e funciona como devido. Porém verifiquei que quando aumenta a quantidade de um produto, o plugin soma as dimensões para calcular. O problema aqui é que se passar do peso e/ou medida aceita pelos Correios, vai retornar um erro no log de peso excedido. Outra coisa é que os pacotes são enviados separados.

Eu consegui tirar a parte da soma e agora retorna o valor de 1 item. O passo seguinte deve ser multiplicar esse valor pela quantidade de itens.

Agora como manipular o valor retornado do webservice? Dando uma pesquisada achei um meio de obter a quantidade de itens no carrinho do wc:
`foreach ( WC()->cart->get_cart() as $cart_item ) {
$quantity = $cart_item['quantity'];
}`

 porém quando aplica ali em $rate (class-wc-correios-shipping.php), 
`'cost' => (float) $cost + (float) $fee * $quantity,`
retorna que não existem métodos de entrega disponíveis.

Creio que o cálculo deveria ser assim por padrão, ou estou errado? Não conheço muito de php mas se os autores ou alguém puder dar uma luz aqui agradeço!

**Comment by OsmarGR2** [comment]
estou com o mesmo problema. precisando calcular o Sedex pela quantidade de itens no carrinho.

**Comment by projetosfsi** [comment]
Conseguiu uma solução para isso?

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
