### ISSUE TITLE
Erro após instalar esse plugin: Uncaught ArgumentCountError: Too few arguments to function WC_Correios_Orders

### ISSUE THREAD

**Issue by Cae2** [claudiosanches/woocommerce-correios#128]
Bom dia Claudio,

Após instalar o plugin dos correios, não consigo mais entrar em nenhum pedido feito em nossa loja que apresenta o erro abaixo (se eu desativar o plugin volta a funcionar a tela de pedido)

O que acha que pode ser? Obrigado!

`1 - Uncaught ArgumentCountError: Too few arguments to function WC_Correios_Orders::item_display_delivery_forecast(), 1 passed in /home4/store/wp-includes/class-wp-hook.php on line 286 and exactly 2 expected in /home4/store/wp-content/plugins/woocommerce-correios/includes/class-wc-correios-orders.php:56 Stack trace: #0 /home4/store/wp-includes/class-wp-hook.php(286): WC_Correios_Orders->item_display_delivery_forecast('Cor') #1 /home4/store/wp-includes/plugin.php(203): WP_Hook->apply_filters('Cor', Array) #2 /home4/store/wp-content/plugins/alidswoo/core/init.php(0): apply_filters('woocommerce_ord...', 'Cor') #3 /home4/store/wp-includes/class-wp-hook.php(286): adsw_before_order_itemmeta(65, Object(WC_Order_Item_Product), Object(WC_Product_Variation)) #4 /home4/store/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #5 /home4/brilhe - /home4/store/wp-content/plugins/woocommerce-correios/includes/class-wc-correios-orders.php - 56`

**Comment by henriquemattos** [comment]
@Cae2 confirma a versão do PHP, WordPress e do Plugin que você está usando, por favor?

**Comment by Cae2** [comment]
opa! bom dia Henrique

Versão do WooCommerce: 3.4.5
Versão do WordPress: 4.9.8
Versão do PHP: 7.2.10
Versão do Plugin: 3.7.1

**Comment by henriquemattos** [comment]
Boa tarde, @Cae2. Parece que você está tendo o [mesmo problema](https://wordpress.org/support/topic/fatal-errors-on-woocommerce-order-page/) que o pessoal que usa o **WooCommerce Product Addons**. Confirma se você está usando esse plugin?

**Comment by Cae2** [comment]
@henriquemattos oie, não tenho esse plugin que você mencionou, mas fiz uns testes e descobri que quando eu desabilito o **AliDropship Woo Plugin** ele funciona... (mas o plugin do AliDropship é importante demais pra eu manter desativado...)

**Comment by henriquemattos** [comment]
Sim, @Cae2 . Depois que postei eu vi que era esse AliDropShipWoo plugin. Infelizmente você vai ter que esperar o seu plugin ser atualizado, visto que o problema não é com o WooCommerce Correios diretamente.
