### ISSUE TITLE
Link para rastreamento (admin) e botão para rastreamento (my-account) não funciona mais.

### ISSUE THREAD

**Issue by luisaurelio** [claudiosanches/woocommerce-correios#129]
Prezados,

Peço a gentileza de trocar a url "http://www2.correios.com.br/sistemas/rastreamento/resultado_semcontent.cfm" por "https://www2.correios.com.br/sistemas/rastreamento/resultado_semcontent.cfm", pois quando o http redireciona para o https ele perde a informação do código de rastreio.

**Comment by henriquemattos** [comment]
Duplicada de #124 e #123
