### ISSUE TITLE
Corporativo Correios

### ISSUE THREAD

**Issue by giovanibboschi** [claudiosanches/woocommerce-correios#131]
Olá.
Tenho uma dúvida quanto a integração "corporativo" dos correios.

No meu caso, entro na opção PAC, por exemplo, e lá tenho a opção de selecionar o "tipo de serviço". Como tenho contrato com os correios e quero que mostre em minha loja o preço do frete com o desconto que agora tenho, insiro ali meu código administrativo e a senha, mas ai no carrinho na loja some a opção PAC. 

Tentei também o mesmo processo com o sedex e ai some a opção sedex no carrinho na loja.

Segundo o pessoal dos correios deveria aparecer no painel outras opções depois que eu insiro ali meu código administrativo e a senha. (cada um fala um coisa, rs)

Enfim, minha dúvida é: É somente por ali mesmo que tenho como me conectar com o CORPORATIVO dos correios? Só selecionar tipo de serviço CORPORATIVO, colocar o codigo e senha e deu? Tem algum outro passo? Porque até agora somente isso não ta funcionando.

Aguardo e desde já agradeço a atenção!

Giovani Boschi

**Comment by filipeestima** [comment]
Quando se tem contrato com os Correios, PAC local deixa de ser oferecido. Ou seja, PAC para a mesma cidade ou para cidades próximas que têm precificação local. Em lugar dele a empresa oferece o SEDEX, que custa mais barato do que o PAC.

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
