### ISSUE TITLE
Erro de login (usuário ou senha) devido a caracteres inválidos na senha

### ISSUE THREAD

**Issue by wjuniorgit** [claudiosanches/woocommerce-correios#132]
Olá, antes de tudo agradeço pelo excelente plugin desenvolvido por vocês!

Estou desenvolvendo uma Loja WooCommerce utilizando o plugin de vocês e detectei um problema em relação as credenciais de acesso inseridas no plugin no SRO dos Correios.

Recebi uma senha gerada automaticamente pelos Correios que inicia com o caractere '>'.
Ao realizar o teste com o usuário e senha informados pelos Correios no SoapUI, a resposta do rastreamento é recebida com sucesso.

Ao inserir o usuário e senha informados nas configurações do Plugin, a tabela de rastreamento não é exibida, e no log eu recebo a informação que o usuário e senha são inválidos.

> 10-24-2018 @ 11:05:10 - Fetching tracking history for "PM**********BR" on Correios Webservices...
> 10-24-2018 @ 11:05:12 - An error occurred while trying to fetch the tracking history for "PM295837123BR": Invalid username or password!

Ao utilizar a senha para testes dos Correios o plugin está funcionando corretamente.

Para tentar entender o que está acontecendo e atender a minha demanda imediata, eu adicionei o meu usuário e senha diretamente no arquivo class-wc-correios-tracking-history.php na função get_tracking_history() e a tabela passou a ser exibida com sucesso. Segue o snippet de código com a alteração simples para funcionamento do plugin com a minha senha.

```
/*'usuario' => $user_data['login'], 
'senha' => $user_data['password'],*/
 'usuario' => '*****',
 'senha' => '>******',
```

Por isso, creio que o fato da senha iniciar com o caractere '>' é o responsável pelo plugin retornar a informação que o usuário e senha são inválidos.

**Comment by claudiosanches** [comment]
Você pode usar os filtros do plugin para lidar com isso.
Vou mudar o tipo de campo para evitar esse problema, obrigado por reportar isso.

**Comment by AlexandreSA** [comment]
Boa tarde,
Estou passando pelo mesmo problema, no meu caso, testei inserindo o usuário e senha dos correios direto e continua com a mensagem de erro.

Quando insiro os dados nos métodos de entrega, o calculo do valor do frete fica mais barato, ou seja, o usuário é valido. 
Fiquei com dúvida quanto a qual usuário eu devo usar para consultar o histórico dos objetos, tentei até o usuário Sigepweb Master e continua com a mensagem.

**Comment by jupinheiro1369** [comment]
Olá bom dia tudo bem?? Estou com o mesmo problema. Alguem consegue me ajudar???

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
