### ISSUE TITLE
Precificação-Internacional

### ISSUE THREAD

**Issue by wubuyun** [claudiosanches/woocommerce-correios#133]
Histórico de Releases
Versão: 2.0.5
Ambientes :
HOMOLOGAÇÃO, 25/06/2018 17:03
PRODUÇÃO, 26/06/2018 10:50
Mudanças:
Ajuste para usuário externo.

Passos necessários para acessar os [link](https://apps.correios.com.br/componentes/home/index.html#/ajuda)

Documentação Completa (Externa): [link](https://cws2.correios.com.br/static/swagger/?url=/precoprazoservice/rs/swagger.json#/Internacional)

**Comment by marcelowu** [comment]
Preços e Prazos Internacionais
O calculador remoto será substituído em breve por um componente mais moderno.
Informamos aos usuários que o calculador atual será desativado 6 meses após a disponibilização da nova ferramenta.
