### ISSUE TITLE
Simulação do cálculo de frete dos correios não bate com o plugin.

### ISSUE THREAD

**Issue by grimpa** [claudiosanches/woocommerce-correios#134]
Com os mesmos dados eu faço uma simulação no site dos correios e da um valor. Mas na loja utilizando o Plugin, retorna um valor bem superior.

Medidas da embalagem (C x L x A): 44cm x 24cm x 10cm
Peso: no máximo 500g

Como eu devo preencher esse valor na loja/plugin/produtos?

**Comment by grimpa** [comment]
Eu coloquei apenas o peso do produto e deu certo.

**Comment by ricardixbr** [comment]
Eu iria abrir uma issue, mas notei que o meu cenário pode ser este msm.

Pelo que notei o webservice dos correios, não está calculando o acréscimo na taxa de manuseio para produtos com comprimento maior que 70cm.

@claudiosanches sabe como posso criar um hook ( ou outra coisa), para adicionar um valor ao frete, só para produtos com comprimento igual ou maior 70 cm

**Comment by claudiosanches** [comment]
Taxa de manuseio não é adicionado pelo Webservice e é sempre somado ao valor total do frete.
