### ISSUE TITLE
Atulizacao do preço no balcão nao repassada p webservice

### ISSUE THREAD

**Issue by ricardixbr** [claudiosanches/woocommerce-correios#135]
Pelo que notei o webservice dos correios, não está calculando o acréscimo na taxa de manuseio para produtos com comprimento maior que 70cm.

sabem como posso criar um hook ( ou outra coisa), para adicionar um valor ao frete, só para produtos com comprimento igual ou maior 70 cm

**Comment by ricardixbr** [comment]
alguem teve o msm problema?

**Comment by claudiosanches** [comment]
Tem alguns filtros do plugin já, mas isso dai tem que vim do Webservice já o valor correto.
Fechando por enquanto, se tiver ainda problema me avisa.
