### ISSUE TITLE
Métodos de Envio Diferentes no Mesmo Carrinho

### ISSUE THREAD

**Issue by siegteshelos** [claudiosanches/woocommerce-correios#136]
Olá,

Estou com uma dúvida que ao que tudo indica é uma limitação do plugin, mas não consegui encontrar uma solução nem no fórum do plugin no wordpress nem em outros tópicos sobre o plugin do correios.

Eu tenho produtos que utilizam o método de envio Impresso e outros que utilizam PAC. Eu configurei duas classes de entrega (impresso e encomenda) e criei também dois métodos de entrega um para o PAC (que está amarrado a encomenda) e outro para Impresso (que eu amarrei com a classe impresso).

Tudo está funcionando bem, consigo calcular o valor do frete se colocar cada um dos produtos em separado no carrinho, mas se colocar dois produtos no mesmo carrinho não consigo calcular o frete combinado. Sempre que há dois produtos no carrinho com classes diferentes, o woocommerce retorna que um dos produtos não tem um método de envio configurado.

Em ambos os casos os produtos estão com peso e dimensões configurados.

**Comment by siegteshelos** [comment]
Olá,

Depois de muita procura consegui entender que o problema não é com o plugin em si, mas a forma como o woocommerce lida com o sistema de múltiplas classes de frete.

**Comment by jeanlorencini** [comment]
Como conseguiu resolver amigo?

**Comment by pbraconnot** [comment]
Mesmo problema aqui. Se tem duas classes de entrega no carrinho o sistema diz "Não existem métodos de entrega disponíveis"
Acho que a solução seria ter uma classe Principal. Caso aconteça o erro o sistema tentaria colocar os produtos na classe principal.
No meu caso tenho a opção de carta registrada mas não serve para todos os produtos.
Neste caso se a classe principal fosse SEDEX, PAC, resolveria o problema para carrinhos que contenham duas classes de entrega.

**Comment by conexaototal** [comment]
Boa tarde!!!
Estou com tudo bem?

Estou com o mesmo problema...

@claudiosanches sabe como resolver isso?


Muito obrigado e fica com Deus!!!
