### ISSUE TITLE
Tirar endereço do cálculo de frete no carrinho

### ISSUE THREAD

**Issue by larinhavgs** [claudiosanches/woocommerce-correios#141]
Oi, estou há uns dias apanhando do cálculo de frete, pois quando coloco um endereço e Cep de Floripa na página de carrinho ele atualiza com o nome da rua que estiver na página de Checkout. Por exemplo: se eu fiz uma compra antes com endereço de Ribeirão Preto e depois volto pro carrinho e coloco um de Floripa ele atualiza os valores mas mantém a rua de Ribeirão preto do preenchimento anterior.  Eu desativo o auto preenchimento de endereço mas não muda nada. Tem como eu tirar esse nome da rua dali? Segue exemplo anexo 
![cep](https://user-images.githubusercontent.com/4535486/49184744-4d4e3a00-f347-11e8-806f-29adeaee6102.jpg)

**Comment by wagnerjaccoud** [comment]
Insira em seu css:

.woocommerce-shipping-destination { display: none !important; }

**Comment by claudiosanches** [comment]
Isso é do WooCommerce e não deste plugin. Fechando já que é uma questão não relacionada.
