### ISSUE TITLE
Impresso Normal não exibe prazo de entrega

### ISSUE THREAD

**Issue by thithiqueiroz** [claudiosanches/woocommerce-correios#142]
Quando todos os métodos de entrega são exibidos no carrinho/checkout, é exibido o prazo de entrega para PAC e SEDEX, exceto para Impresso Normal.

**Comment by claudiosanches** [comment]
Não tem webservice para isso, então não tem como ter uma previsão dos Correios sobre a entrega.
Se você souber de algum endpoint da API deles que faça isso, favor me avisar.

**Comment by gutobenn** [comment]
Sei que para Impresso Normal com contrato (meu cliente usa o 20150, talvez tenha outros) o endpoint `http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx/CalcPrazoData` retorna essas informações.
