### ISSUE TITLE
Valor da loja do correio muito diferente

### ISSUE THREAD

**Issue by FernandaFil** [claudiosanches/woocommerce-correios#143]
Cláudio,
Sabemos que é uma estimativa aproximada e depende das configurações. Porém encontrei um problema no envio para o Rio de Janeiro.
Além do pac/sedex ter o valor maior que o da loja (mesmas configurações de peso, medidas etc) aparece no plugin uma taxa FRETE RJ.
Fui aos Correios e eles disseram que não existe mais esta taxa.
Tive que reembolsar este valor para o cliente que comprou pela loja.

Com relação aos valores, sempre dá uma diferença, por ex. de 31,40 para 35,01. Esta variação é normal mesmo? Não teremos um valor exato?

Seguem os prints para você conferir.

Grata
Fernanda

![1](https://user-images.githubusercontent.com/45941945/50355193-ffd38000-0534-11e9-9f3d-4fd2c84f21a7.JPG)
![2](https://user-images.githubusercontent.com/45941945/50355194-ffd38000-0534-11e9-8642-91a3a27c658f.JPG)
![3](https://user-images.githubusercontent.com/45941945/50355195-006c1680-0535-11e9-8dbd-686fb9230b3a.JPG)
![4](https://user-images.githubusercontent.com/45941945/50355196-006c1680-0535-11e9-8785-7bfb19b833a7.JPG)

**Comment by claudiosanches** [comment]
> Com relação aos valores, sempre dá uma diferença, por ex. de 31,40 para 35,01. Esta variação é normal mesmo? Não teremos um valor exato?

O valor vêm do Webservice dos Correios, da para ver no log do plugin o que é enviado e como é feita a URL do XML do webservices.
Se tem diferença de valor, ou é o que você configurou ou o que o Webservice dos Correios esta respondendo.
