### ISSUE TITLE
Não existem métodos de entrega disponíveis. Certifique-se de que o seu endereço foi preenchido corretamente, ou entre em contato conosco se precisar de ajuda.

### ISSUE THREAD

**Issue by xguiboy** [claudiosanches/woocommerce-correios#146]
Tenho utilizado esse plugin a uns dois anos já, e nunca deu problema, agora está aparecendo essa mensagem para qualquer CEP que eu coloque, já exclui os logs, reinstalei e nada. Será se é o sistema dos correios que está fora do ar? Meu site https://www.isopasse.com.br

**Comment by thiagolcks** [comment]
Estamos tendo esse problema direto, e pelo que vi é problema de timeout. Honestamente, estamos tendo que desativar o plugin dos correios pq não está sendo possível usar ele com esse problema.

Agora estou buscando algum método alternativo de ter o cálculo dos correios.

@claudiosanches alguma sugestão?

**Comment by claudiosanches** [comment]
Servidor dos Correios caiu, então não adianta, problema não é o plugin, precisa deles voltarem.
