### ISSUE TITLE
Different API call for a marketplace with multiple sellers.

### ISSUE THREAD

**Issue by andreagrillo** [claudiosanches/woocommerce-correios#148]
Hola Claudio, 
Douglass tell me to post the question here. I write heere the same question from wp.org:

> Hi there,
> 
> Thanks for this fantastic plugin, works like a charm 🙂
> I need an information about your plugin. I have a Multi Vendor website and I want that each seller can set their own shipping cost. I think to integrate your plugin in my website and I have found a way to replicate the shipping options for each vendor, save and retrieve it without issue.
> I need that you plugin make multiple call to Correios, and set different shipping cost for the different vendors.
> 
> In example if in the cart I have products from 3 different seller, I want to group the products by vendor and then calculate the shipping cost for each group of products. I don’t need that you send to me the full code, but simply tell me if I can use some hooks/action to do that, I’m a developer.
> 
> I hope that you can help me with this request.
> Have a nice day
> 

Thanks for your help.
Have a nice day 
Andrea

**Comment by luizbills** [comment]
You can split the cart in many packages. Each package will have its own delivery cost.

The sender zip code you can change with a hook filter: https://github.com/claudiosanches/woocommerce-correios/blob/master/includes/class-wc-correios-webservice.php#L425

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
