### ISSUE TITLE
Problema com Áreas de Entrega

### ISSUE THREAD

**Issue by codiworks** [claudiosanches/woocommerce-correios#149]
Configurei duas áreas de entrega, uma para as regiões norte e nordeste e outra para as demais regiões do Brasil. Em ambas, configurei em "Regiões da Área", os estados das regiões. No entanto, alguns problemas estão surgindo na hora de realizar o cálculo do frete. Mesmo inserindo o CEP e o nome da cidade, ele mantém o meu estado (quando eu realizo o teste de cálculo de frete). Solicitei que uma pessoa em outro estado fizesse o teste, e para essa pessoa já aparece a mensagem: "Nenhuma opção de entrega foi encontrada".

O que posso estar fazendo de errado?

Obs: As informações de peso e dimensões estão devidamente configuradas.

**Comment by claudiosanches** [comment]
Área de entregas não faz parte desse plugin, elas são do WooCommerce, se tiver dúvida sobre isso é melhor procurar um fórum sobre o WooCommerce, aqui só consigo responder o que for sobre o plugin dos Correios e pelo o que você esta falando, parece configuração das suas áreas de entrega.
