### ISSUE TITLE
Mensagem errada para entrega em áreas de risco

### ISSUE THREAD

**Issue by castrocarol** [claudiosanches/woocommerce-correios#151]
Os correios pararam de fazer a entrega em algumas áreas, que para eles são consideradas áreas de risco. Para isso, quando é consultado na página de preços e prazos do site dos correios, aparece a seguinte mensagem:
_"O CEP de destino está temporariamente sem entrega domiciliar. A entrega será efetuada na agência indicada no Aviso de Chegada que será entregue no endereço do destinatário."_

Quando um cep de uma área de risco é colocado para fazer o cálculo do frete no plugin, a mensagem que aparece é:
          _"Área com entrega temporariamente sujeita a prazo diferenciado."_

Acontece que não é um prazo diferenciado, eles não farão a entrega e o cliente precisará retirar no centro de distribuição.

A mensagem dos correios deixa claro que o cliente deverá buscar o pacote na agência, enquanto a mensagem que o plugin mostra apenas fala de prazo diferenciado.

Precisa ajustar essa mensagem pois estou tendo problemas com clientes que exigem a devolução do valor do frete, visto que no site em que estou usando o plugin dá a entender que a pessoa receberá o produto em casa, e não que terá que retirar na agencia.

**Comment by CasperBraske** [comment]
Acho que isso aqui resolve temporariamente:

```php

add_filter('woocommerce_correios_available_error_messages',function( $messages ){

	$messages['011'] = 'O CEP de destino está temporariamente sem entrega domiciliar. A entrega será efetuada na agência indicada no Aviso de Chegada que será entregue no endereço do destinatário.';

	return $messages;
});
```

**Comment by claudiosanches** [comment]
As mensagens que o plugin usa são as sugeridas pela documentação do Webservice dos Correios.
