### ISSUE TITLE
Problemas

### ISSUE THREAD

**Issue by guibarbas** [claudiosanches/woocommerce-correios#152]
Olá, bom dia.

Hoje notei que todos meus sites com o sistema dos correios está retornando a mesma mensagem de erro.

**Nenhuma opção de entrega foi encontrada para Cidade, Estado, Cep.
Digite um endereço diferente**

Realizei o teste em vários sites e o mesmo erro ocorre.
**Estes sites estavam funcionando normalmente**

Veja os logs.
Em um dos sites 
https://pastebin.com/B2GbEE8f
https://pastebin.com/u2VPkLK7

Em outro site
https://pastebin.com/WWEs3VV8
https://pastebin.com/cGY9bKaE

Poderiam me ajudar 
?

**Comment by aas2512** [comment]
Site que tambem faço uso do plugin esta apresentando a mesma mensagem , desde que vinha funcionando tudo corretamente.

**Comment by rafatriolo** [comment]
Estou com o mesmo problema! Ele faz a cotação pelo webservice, retorna para a loja, mas não mostra no frontend!

**Comment by guibarbas** [comment]
Pessoal, identifiquei a correção.

No fórum do WP o amigo Matheus Almeida (@matheusweb)
Indicou a solução "Talvez paliativa" 


https://wordpress.org/support/topic/log-mostra-calculo-dos-correios-porem-no-carrinho-finalizacao-nao-encontra-envio/

No arquivo woocommerce-correios\includes\abstracts\class-wc-correios-shipping.php

Na linha 439, abaixo de:
$codes[] = '0';
Adicionar:
$codes[] = '';

`	protected function get_accepted_error_codes() {
		$codes   = apply_filters( 'woocommerce_correios_accepted_error_codes', array( '-33', '-3', '010', '011' ) );
		$codes[] = '0';
		$codes[] = ''; //adicionar esta linha

		return $codes;
	}`

**Comment by rafatriolo** [comment]
eu fiz e não deu certo!

**Comment by guibarbas** [comment]
> eu fiz e não deu certo!

Lembra de atualizar ou testar de outro navegador

**Comment by matheusweb** [comment]
Rafael, outras causas desse problema podem ser:
- produto sem peso configurado
- configurações dos Correios sem CEP de origem
- configurações dos Correios sem dimensões e peso padrão

Tente ativar os logs para ver mais detalhes e mudar para outros CEPs na
hora de testar

Em seg, 6 de mai de 2019 às 11:37, Rafael Triolo <notifications@github.com>
escreveu:

**Comment by rafatriolo** [comment]
@matheusweb e @guibarbas eu ja tinha feito tudo o que vcs falaram acima, estava fucionando e de repdente parou. segue abaixo o ultimo log:

05-06-2019 @ 11:37:15 - Requesting Correios WebServices: http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?nCdServico=04510&nCdEmpresa&sDsSenha&sCepDestino=06711250&sCepOrigem=04047001&nVlAltura=2&nVlLargura=11&nVlDiametro=0&nVlComprimento=16&nVlPeso=0,4&nCdFormato=1&sCdMaoPropria=N&nVlValorDeclarado=0&sCdAvisoRecebimento=N&StrRetorno=xml
05-06-2019 @ 11:37:21 - Correios WebServices response: SimpleXMLElement Object
(
    [cServico] => SimpleXMLElement Object
        (
            [Codigo] => 04510
            [Valor] => 19,80
            [PrazoEntrega] => 5
            [ValorSemAdicionais] => 19,80
            [ValorMaoPropria] => 0,00
            [ValorAvisoRecebimento] => 0,00
            [ValorValorDeclarado] => 0,00
            [EntregaDomiciliar] => S
            [EntregaSabado] => N
            [Erro] => SimpleXMLElement Object
                (
                )

            [MsgErro] => SimpleXMLElement Object
                (
                )

            [obsFim] => SimpleXMLElement Object
                (
                )

        )

)

**Comment by aas2512** [comment]
@guibarbas  Obrigado! Funcionou...

**Comment by matheusweb** [comment]
Rafael,
O retorno parece que está certo, o meu também estava assim (mostrando valor
do frete no log, mas não mostrava no site)
Nesse caso o ajuste no código resolveu:

protected function get_accepted_error_codes() {
    $codes = apply_filters( 'woocommerce_correios_accepted_error_codes',
array( '-33', '-3', '010', '011' ) );
    $codes[] = '0';
    $codes[] = ''; //adicionar esta linha
return $codes; }


Veja se o arquivo PHP alterado é esse mesmo:
woocommerce-correios\includes\abstracts\class-wc-correios-shipping.php

Em seg, 6 de mai de 2019 às 11:46, Rafael Triolo <notifications@github.com>
escreveu:

**Comment by rafatriolo** [comment]
@matheusweb eu coloquei o código e continua não aparecendo.

último log:

05-06-2019 @ 12:03:55 - Weight and cubage of the order: Array
(
    [weight] => 0,4
    [height] => 2
    [width] => 11
    [length] => 16
)

05-06-2019 @ 12:03:55 - Requesting Correios WebServices: http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?nCdServico=04510&nCdEmpresa&sDsSenha&sCepDestino=06711250&sCepOrigem=04047001&nVlAltura=2&nVlLargura=11&nVlDiametro=0&nVlComprimento=16&nVlPeso=0,4&nCdFormato=1&sCdMaoPropria=N&nVlValorDeclarado=0&sCdAvisoRecebimento=N&StrRetorno=xml
05-06-2019 @ 12:03:59 - Correios WebServices response: SimpleXMLElement Object
(
    [cServico] => SimpleXMLElement Object
        (
            [Codigo] => 04510
            [Valor] => 19,80
            [PrazoEntrega] => 5
            [ValorSemAdicionais] => 19,80
            [ValorMaoPropria] => 0,00
            [ValorAvisoRecebimento] => 0,00
            [ValorValorDeclarado] => 0,00
            [EntregaDomiciliar] => S
            [EntregaSabado] => N
            [Erro] => SimpleXMLElement Object
                (
                )

            [MsgErro] => SimpleXMLElement Object
                (
                )

            [obsFim] => SimpleXMLElement Object
                (
                )

        )

)

**Comment by rafatriolo** [comment]
se quiser dá uma olhada no site https://psicotropica.com.br. Obrigado!

**Comment by guibarbas** [comment]
> se quiser dá uma olhada no site https://psicotropica.com.br. Obrigado!

Amigo, acredito que tem alguma config errada em seu sistema.

Fiz o teste com 2 ceps aqui de Ribeirão preto e Campinas e ambos exibem **Retirar no Ateliê**

http://prntscr.com/nl4wcf
http://prntscr.com/nl4x2h

**Comment by AleSilvabrAiPress** [comment]
Obrigado pessoal... coloquei aqui e deu certíssimo...

**Comment by rafatriolo** [comment]
> > se quiser dá uma olhada no site https://psicotropica.com.br. Obrigado!
> 
> Amigo, acredito que tem alguma config errada em seu sistema.
> 
> Fiz o teste com 2 ceps aqui de Ribeirão preto e Campinas e ambos exibem **Retirar no Ateliê**
> 
> http://prntscr.com/nl4wcf
> http://prntscr.com/nl4x2h

Sim, pq esse é o metodo padrão, se eu retirar essa opção mostra que não tem nenhuma opção disponivel.

**Comment by guibarbas** [comment]
> > > se quiser dá uma olhada no site https://psicotropica.com.br. Obrigado!
> > 
> > 
> > Amigo, acredito que tem alguma config errada em seu sistema.
> > Fiz o teste com 2 ceps aqui de Ribeirão preto e Campinas e ambos exibem **Retirar no Ateliê**
> > http://prntscr.com/nl4wcf
> > http://prntscr.com/nl4x2h
> 
> Sim, pq esse é o metodo padrão, se eu retirar essa opção mostra que não tem nenhuma opção disponivel.

Como esta a config de seus fretes ?

**Comment by rafatriolo** [comment]
segue

![4](https://user-images.githubusercontent.com/13166395/57235765-fdf8ed80-6ff9-11e9-9d73-004ef99c6fa3.PNG)
![1](https://user-images.githubusercontent.com/13166395/57235766-fdf8ed80-6ff9-11e9-8f50-421a4468abf3.PNG)
![2](https://user-images.githubusercontent.com/13166395/57235768-fdf8ed80-6ff9-11e9-9a2c-d00ab6f02781.PNG)
![3](https://user-images.githubusercontent.com/13166395/57235769-fdf8ed80-6ff9-11e9-9f73-273cb0bd7f10.PNG)

**Comment by guibarbas** [comment]
> segue
> 
> ![4](https://user-images.githubusercontent.com/13166395/57235765-fdf8ed80-6ff9-11e9-9d73-004ef99c6fa3.PNG)
> ![1](https://user-images.githubusercontent.com/13166395/57235766-fdf8ed80-6ff9-11e9-8f50-421a4468abf3.PNG)
> ![2](https://user-images.githubusercontent.com/13166395/57235768-fdf8ed80-6ff9-11e9-9a2c-d00ab6f02781.PNG)
> ![3](https://user-images.githubusercontent.com/13166395/57235769-fdf8ed80-6ff9-11e9-9f73-273cb0bd7f10.PNG)

Confirma se seus códigos de serviço estão corretos
Pagamento à vista (Sem contrato)
Sedex: 4014
PAC: 4510

Contrato Encomenda 2.0 
Sedex: 4553
PAC: 4596

Outros contratos 2.1 e etc
Sedex: 4162
PAC: 4669

**Comment by rafatriolo** [comment]
@guibarbas  estão certo sim!

**Comment by matheusweb** [comment]
Rafael o peso padrão está com ponto ou com vírgula?
O meu deixo sempre com ponto e funciona:
0.4

Em seg, 6 de mai de 2019 12:40, Rafael Triolo <notifications@github.com>
escreveu:

**Comment by rafatriolo** [comment]
esta com ponto 0.400

**Comment by dadeke** [comment]
@matheusweb e @guibarbas 

Deu certo aqui também.

Por favor, se puderem, envie um _"pull request"_ para o @claudiosanches avaliar se essa solução é paliativa ou definitiva.

Muito obrigado pela colaboração de vocês!

**Comment by lucianomb** [comment]
Aqui também funcionou a solução que o @guibarbas apontou, mas só depois que mudei o peso "extra" de **".3"** para **"0.3"**.

**Comment by guibarbas** [comment]
> @matheusweb e @guibarbas
> 
> Deu certo aqui também.
> 
> Por favor, se puderem, envie um _"pull request"_ para o @claudiosanches avaliar se essa solução é paliativa ou definitiva.
> 
> Muito obrigado pela colaboração de vocês!

https://github.com/claudiosanches/woocommerce-correios/pull/153

**Comment by hmhallak** [comment]
> Pessoal, identifiquei a correção.
> 
> No fórum do WP o amigo Matheus Almeida (@matheusweb)
> Indicou a solução "Talvez paliativa"
> 
> https://wordpress.org/support/topic/log-mostra-calculo-dos-correios-porem-no-carrinho-finalizacao-nao-encontra-envio/
> 
> No arquivo woocommerce-correios\includes\abstracts\class-wc-correios-shipping.php
> 
> Na linha 439, abaixo de:
> $codes[] = '0';
> Adicionar:
> $codes[] = '';
> 
> protected function get_accepted_error_codes() {
> $codes = apply_filters( 'woocommerce_correios_accepted_error_codes', array( '-33', '-3', '010', '011' ) );
> $codes[] = '0';
> $codes[] = ''; //adicionar esta linha
> 
> ```
> 	return $codes;
> }
> ```

Deu certo! Valeu!!

**Comment by claudiosanches** [comment]
Engraçada que ainda para mim aparece como `0`, incrível também que só ficamos sabendo dessas coisas quando param, os Correios nunca avisa ninguém.
Obrigado por depurarem esse problema, estou lançando uma versão nova agora.

**Comment by claudiosanches** [comment]
Corrigido em #153

**Comment by rafatriolo** [comment]
funcionou pra mim tbm galera, por algum motivo estava pegando cache!

**Comment by rafatriolo** [comment]
muito obrigado pela ajuda.

**Comment by joaolucasbraganca** [comment]
Senhores,

No meu código, já existe essa linha e para alguns produtos é calculado  o PAC e para outros não.
