### ISSUE TITLE
Integração com o WCFM WCLovers

### ISSUE THREAD

**Issue by guibarbas** [claudiosanches/woocommerce-correios#155]
Olá @claudiosanches  como vai mestre ?

Gostaria de saber se é possível integrar seu plugin ao WCFM da WCLovers
https://wordpress.org/plugins/wc-frontend-manager/
(Gratuito)

Vi que neste post https://github.com/claudiosanches/woocommerce-correios/issues/108 (antigo já) você iria integrar com o dokan

Será que seria possível com o WCLovers ?
Seria muito bom esta opção, para poder ao menos obter o cep de cada loja e poder calcular.

Tenho o contato direto com o suporte Premium do plugin, caso precise.

**Comment by claudiosanches** [comment]
Fica a vontade para fazer essa integração, você mesmo pode fazer um plugin para integrar os dois, entretanto não tenho interesse em integrar isso no momento. Boa sorte.
