### ISSUE TITLE
Não encontra o CEP e consequentemente o FRETE

### ISSUE THREAD

**Issue by dankhairalla** [claudiosanches/woocommerce-correios#156]
Olá claúdo,

Meu problema é que hora aparece os valores quando inseri o CEP e outra hora ele fala que não tem o CEP pra região... segue o logo:

05-09-2019 @ 10:40:10 - Weight and cubage of the order: Array
(
    [weight] => 0,3
    [height] => 10
    [width] => 11
    [length] => 16
)

05-09-2019 @ 10:40:10 - Requesting Correios WebServices: http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?nCdServico=04510&nCdEmpresa&sDsSenha&sCepDestino=37800000&sCepOrigem&nVlAltura=10&nVlLargura=11&nVlDiametro=0&nVlComprimento=16&nVlPeso=0,3&nCdFormato=1&sCdMaoPropria=N&nVlValorDeclarado=160&sCdAvisoRecebimento=N&StrRetorno=xml
05-09-2019 @ 10:40:16 - Correios WebServices response: SimpleXMLElement Object
(
    [cServico] => SimpleXMLElement Object
        (
            [Codigo] => 04510
            [Valor] => 0
            [PrazoEntrega] => 0
            [ValorMaoPropria] => 0
            [ValorAvisoRecebimento] => 0
            [ValorValorDeclarado] => 0
            [ValorSemAdicionais] => 0
            [EntregaDomiciliar] => SimpleXMLElement Object
                (
                )

            [EntregaSabado] => SimpleXMLElement Object
                (
                )

            [Erro] => -1
            [MsgErro] => ERP-005: CEP inexistente (). --> UF ORIGEM
        )

)

**Comment by claudiosanches** [comment]
Basta clicar no link ai ou ler a mensagem dos correios:

`<MsgErro>CEP de origem invalido.</MsgErro>`

A mensagem é clara, os Correios esta lhe dizendo que o seu CEP é inválido, no caso o CEP de origem que você usou na hora de configurar os métodos de entrega deste plugin.
Lembrando que quem cuida do cadastro de CEPs é os Correios, então se o Webservice deles esta lhe dizendo que o CEP é inválido é porque realmente tem algo muito errado com a informação que você esta usando.
