### ISSUE TITLE
Peso total do pedido

### ISSUE THREAD

**Issue by ChicoCybergoth** [claudiosanches/woocommerce-correios#157]
Prezados, há alguma forma de aparecer o peso total do pedido nos detalhes do pedido?
Havendo esse dado consigo colocar ele para imprimir pelo plugin "WooCommerce PDF Invoices & Packing Slips" ?

Grato.

**Comment by CasperBraske** [comment]
Isso é uma funcionalidade a se procurar no WooCommerce, não nesse plugin.

**Comment by claudiosanches** [comment]
Isso é fora do escopo deste plugin, este plugin apenas funciona para integrar os métodos de entrega dos Correios com o WooCommerce, isso que você esta querendo deve ser feito no próprio WooCommerce.
