### ISSUE TITLE
Link para a documentação do Webservices Correios

### ISSUE THREAD

**Issue by Rahmon** [claudiosanches/woocommerce-correios#161]
Olá.

Notei que o link para a documentação do Webservices Correios leva para uma página que não existe mais no site dos Correios. Encontrei a documentação na URL http://www.correios.com.br/a-a-z/pdf/calculador-remoto-de-precos-e-prazos/manual-de-implementacao-do-calculo-remoto-de-precos-e-prazos , que está [nessa página](http://www.correios.com.br/precos-e-prazos/calculador-remoto-de-precos-e-prazos).

**Comment by henriquemattos** [comment]
@Rahmon, aonde no plugin fica o link? Eu poderia criar um PR mas eu não sei especificamente de qual link você está falando... Teria como descrever o caminho até o link?

Abs, Henrique Mattos

**Comment by henriquemattos** [comment]
Seria esse aqui: http://www.correios.com.br/webservices/ ??

**Comment by henriquemattos** [comment]
Acho que esse PR cobre os dois casos, vamos aguardar review.

#163

**Comment by Rahmon** [comment]
Exatamente nesses dois arquivos que você alterou na PR.
