### ISSUE TITLE
Execução infinita do método WC_Correios_Install::upgrade_300

### ISSUE THREAD

**Issue by jsvini** [claudiosanches/woocommerce-correios#162]
Notei que o método WC_Correios_Install::upgrade_300 é executado a cada exibição de página, realizando um update no DB, creio que seja um bug.

![image](https://user-images.githubusercontent.com/4185886/63551396-71702d80-c50b-11e9-8e0e-1124174dd18b.png)

Notei que o métodos WC_Correios_Install::update_version não é chamado, o que impediria a execução repetida:

https://github.com/claudiosanches/woocommerce-correios/blob/master/includes/class-wc-correios-install.php#L31

**Comment by claudiosanches** [comment]
Obrigado por reportar isso.
