### ISSUE TITLE
Problema com a Linguagem do meu plugin

### ISSUE THREAD

**Issue by daqniwloe** [claudiosanches/woocommerce-correios#164]
Meu wordpress está 100% em português, porém exclusivamente os plugins woocommerce Correios e Woocommerce Pagseguro Estão em inglês ... como faço para resolver isso ??? 

https://user-images.githubusercontent.com/13256524/63957762-6b280700-ca5f-11e9-881b-d82451a8864d.jpg

**Comment by CasperBraske** [comment]
Você checou na parte em Painel > Atualizações se existem atualizações de tradução? Isso pode ser também problema de permissão de arquivos.

**Comment by daqniwloe** [comment]
> Isso pode ser também problema de permissão de arquivos

Sim, já chequei sim! Não existem nenhuma atualização sequer para serem feitas.. Se for permissão de arquivos, como se resolve ?

**Comment by daqniwloe** [comment]
Todas as permissões de arquivos foram corrigidas, porém os plugins continuam em Inglês .... =(

**Comment by CasperBraske** [comment]
Já tentou desinstalar e instalar de novo?

A saber, os arquivos de tradução devem estar em `wp-content/languages/plugins`.

**Comment by daqniwloe** [comment]
Sim. Já desinstalei e instalei várias e várias vezes. Sobre essa pasta, tem vários arquivos do woocommerce que estão em PT 
![PrtScr capture_4](https://user-images.githubusercontent.com/13256524/64130518-3090d800-cd99-11e9-8f86-de357cf001a4.jpg)

**Comment by daqniwloe** [comment]
Era pra ter um tradutor específico para o woocommerce correios ? Porque não tem. Só tem o do woocommerce.

**Comment by daqniwloe** [comment]
> Já tentou desinstalar e instalar de novo?
> 
> A saber, os arquivos de tradução devem estar em `wp-content/languages/plugins`.

Alguma outra sugestão ?

**Comment by henriquemattos** [comment]
@daqniwloe, seu WordPress  está em Português de Portugal (pt_PT) e o WooCommerce Correios/PagSeguro só mantêm a versão Português Brasil (pt_BR).

Ou você muda seu WordPress pra Português do Brasil (pt_BR) ou contribui a tradução pra Português de Portugal (pt_PT).

;)

**Comment by daqniwloe** [comment]
> @daqniwloe, seu WordPress está em Português de Portugal (pt_PT) e o WooCommerce Correios/PagSeguro só mantêm a versão Português Brasil (pt_BR).
> 
> Ou você muda seu WordPress pra Português do Brasil (pt_BR) ou contribui a tradução pra Português de Portugal (pt_PT).
> 
> ;)

Tu é genial cara !! Me resolveu um problema de muito tempo hahaha. Muito grato a você !!!

**Comment by claudiosanches** [comment]
Traduzido esta apenas para Português do Brasil, se você mora em Portugual, é melhor fazer a tradução para a versão apropriada para você.
