### ISSUE TITLE
Setar o custo fixo por tipo de frete

### ISSUE THREAD

**Issue by odirlon** [claudiosanches/woocommerce-correios#165]
Oi, tudo certo? 

Pessoal tenho um cliente que usa uma taxa fixa por tipo de frete. Atualmente usamos esse  código para setar o valor: 

```
function wc_ninja_change_flat_rates_cost( $rates, $package ) {
	// AM,CE,PA,AP,PR - SEDEX
	 if ( isset( $rates['correios-sedex22'] ) ) {
		$rates['correios-sedex22']->cost = 15;
	}
	return $rates;
}
add_filter( 'woocommerce_package_rates', 'wc_ninja_change_flat_rates_cost', 10, 2 );
```

E isso funciona muito bem, o problema é que seria legal ter essa opção de forma nativa, mas para não enxer o plugin de frescura tive uma ideia que poderia ficar muito bacana! 

No campo "Taxa de manuseio" dentro da configuração do frete, se fosse habilitado a opção de calculo, daria para fazer assim: ([custodofrete] - 100%) + 15. 

Assim daria para deixar um valor fixo por tipo de frete, sem o cliente precisar programar. 

Claro que se desse para colocar um campo para poder setar o custo, tb seria legal. 

O que acham da ideia?

**Comment by claudiosanches** [comment]
Já tem opção de taxa de manuseio, além se for fixo assim para alguns estados você nem precisa do plugin dos Correios, consegue usando as áreas de entrega do WooCommerce o método de taxa fixa também do WooCommerce.
