### ISSUE TITLE
 PHP Fatal error: Uncaught Error: Call to a member function

### ISSUE THREAD

**Issue by diegofcv** [claudiosanches/woocommerce-correios#166]
Olá,

Após a instalação e ativação do Plugin, o site deixou de funcionar e apresentou o erro abaixo na log. Foi preciso remover o plugin para restabelecer o site, mas gostaria de resolver o problema para poder utilizar o plugin. Sei que é alguma questão localizada, pois eu testei o plugin em outra instalação do WP e funcionou. Alguma ideia ou sugestão? 

Grato,
Diego

[Mon Sep 30 16:51:48.916342 2019] [fcgid:warn] [pid 29005] [client <<ip>>:58580] mod_fcgid: stderr: PHP Fatal error: Uncaught Error: Call to a member function get_states() on null in /var/www/clients/client1/web8/web/pages/wp-content/plugins/woocommerce-correios/includes/abstracts/class-wc-correios-shipping-international.php:81, referer: https://<<site>>/pages/wp-admin/update.php?action=upload-plugin
[Mon Sep 30 16:51:48.916379 2019] [fcgid:warn] [pid 29005] [client <<ip>>:58580] mod_fcgid: stderr: Stack trace:, referer: https://<<site>>/pages/wp-admin/update.php?action=upload-plugin
[Mon Sep 30 16:51:48.916385 2019] [fcgid:warn] [pid 29005] [client <<ip>>:58580] mod_fcgid: stderr: #0 /var/www/clients/client1/web8/web/pages/wp-content/plugins/woocommerce-correios/includes/abstracts/class-wc-correios-shipping-international.php(35): WC_Correios_Shipping_International->init_form_fields(), referer: https://<<site>>/pages/wp-admin/update.php?action=upload-plugin
[Mon Sep 30 16:51:48.916390 2019] [fcgid:warn] [pid 29005] [client <<ip>>:58580] mod_fcgid: stderr: #1 /var/www/clients/client1/web8/web/pages/wp-content/plugins/woocommerce-correios/includes/shipping/class-wc-correios-shipping-mercadoria-expressa.php(37): WC_Correios_Shipping_International->__construct(0), referer: https://<<site>>/pages/wp-admin/update.php?action=upload-plugin
[Mon Sep 30 16:51:48.916395 2019] [fcgid:warn] [pid 29005] [client <<ip>>:58580] mod_fcgid: stderr: #2 /var/www/clients/client1/web8/web/pages/wp-content/plugins/woocommerce/includes/class-wc-shipping.php(194): WC_Correios_Shipping_Mercadoria_Expressa->__construct(), referer: https://<<site>>/pages/wp-admin/update.php?action=upload-plugin
[Mon Sep 30 16:51:48.916400 2019] [fcgid:warn] [pid 29005] [client <<ip>>:58580] mod_fcgid: stderr: #3 /var/www/clients/client1/web8/web/pages/wp-content/plugins/woocommerce/includes/class-wc-shipping.php(172): WC_Shipping->register_shipping_method(‘WC_Correios_Shi…’), referer: https://<<site>>/pages/wp-admin/update.php?action=upload-plugin
[Mon Sep 30 16:51:48.916405 2019] [fcgid:warn] [pid 29005] [client <<ip>>:58580] mod_fcgid: stderr: #4 /var/www/clients/client1/web8/web/pages/wp in /var/www/clients/client1/web8/web/pages/wp-content/plugins/woocommerce-correios/includes/abstracts/class-wc-correios-shipping-international.php on line 81, referer: https://<<site>>/pages/wp-admin/update.php?action=upload-plugin

**Comment by henriquemattos** [comment]
`https://<>/pages/wp-admin/update.php?action=upload-plugin` Did you sanitize it or do you have any problem with your URL or [virtual] host?

Além disso, pode confirmar que a outra instalação também roda em mod_fcgid e não em mod_php?

**Comment by diegofcv** [comment]
Grato pelo retorno.

A URL foi sanitizada sim. No original ela está OK. Tudo mais funciona bem.

Na outra instalação está igual, fcgi. A versão do PHP estava diferente lá, mas eu configurei a mesma para conferir (7.3.9) e não mudou nada - ou seja, continuou funcionando bem na outra instância, mas quebra na principal...

Tem alguma coisa que o plugin adicione no banco de dados na hora da instalação?

**Comment by henriquemattos** [comment]
Verificando a linha 81 do arquivo **woocommerce-correios/includes/abstracts/class-wc-correios-shipping-international.php** ele usa a global WC (WooCommerce) e puxa a lista de países.

`'options'     => WC()->countries->get_states( 'BR' ),`

Pode confirmar que você **instalou o WooCommerce antes de instalar o WooCommerce-Correios**??

**Comment by diegofcv** [comment]
Sim, o WooCommerce já estava instalado e em uso antes da instalação co WC-Correios.

Grato.

**Comment by claudiosanches** [comment]
@diegofcv o WooCommerce esta atualizado? Porque isso deveria ser carregado apenas quando o WooCommerce já inicializou a class `WC_Countries`, mas parece que na sua instalação isso não aconteceu.

**Comment by claudiosanches** [comment]
Acabei de testar com WooCommerce 3.7 e a última versão do plugin dos Correios e funciona sem nenhum problema.
Será algum plugin esta chamando essas classes de entrega mais cedo do que deveria? Talvez algum plugin para marketplace?

**Comment by diegofcv** [comment]
Oi Cládio, sim o WC está na última versão. Como eu comentei, eu concordo, funciona sim, apenas nesta instalação estou tendo esse problema. Mas é uma instalação que já tem muita coisa, não posso abrir mão dela e começar novamente. Então estava tentando saber o que poderia estar causando o problema. O comentário sobre outros plugins ajuda. Amanhã vou tentar desabilitar os outros plugins para ver se algum deles permite o funcionamento do Correios.

Grato!

**Comment by diegofcv** [comment]
Caros,

Achei o "culpado", vou deixar o registro aqui caso ocorra o mesmo com alguém, já fica a dica do que pode ser.

O outro plugin que estava conflitando com o Correios era o "Woocommerce Payment Gateway Per Product" (https://wordpress.org/plugins/woocommerce-product-payments/). Fui desativando os plugins possíveis e cheguei neste. 

Grato pela ajuda e atenção. Abs!

**Comment by claudiosanches** [comment]
Que estranho isso, porque esse método precisa estar já iniciado, talvez esse outro plugin esta removendo o registro e registrando de novo depois, mas bem estranho.
