### ISSUE TITLE
Loja não mostra opções de entrega, apenas: Retirar no local

### ISSUE THREAD

**Issue by alanvictorjp** [claudiosanches/woocommerce-correios#169]
Instalei a versão mais recente do wordpress com plugins do pagseguro e correios mais recentes, mas o plugin do correios não está exibindo opções de entrega, já fiz vários testes de configurações e sem sucesso, no carrinho só mostra a opção: Retirar no local, alguma ideia do problema?

**Comment by alanvictorjp** [comment]
Erro meu na criação do produto! RESOLVIDO!

**Comment by rickdroio** [comment]
@alanvictorjp o que você fez para corrigir seu produto? estou com o mesmo problema, meu produto tem peso e dimensões... coloquei opções de frete PAC/SEDEX corporativo e convencional para testes, mas nenhum deles aparece. Nenhum LOG é gerado também. O woocomerce está selecionando corretamente a região, porém só deixa "retirar no local" disponível.
Valeu!!!
