### ISSUE TITLE
Problemas com a forma de entrega

### ISSUE THREAD

**Issue by bjrcarlos** [claudiosanches/woocommerce-correios#170]
O plugin não reconhece as formas de entrega SEDEX e PAC.

![image](https://user-images.githubusercontent.com/4383507/67590255-edb40680-f730-11e9-9838-c048213bf23a.png)

Já fiz vários testes de incompatibilidade de plugins e o problema persiste.
Fiz vários testes com endereços e o problema persiste.

As zonas de entrega estão devidamente configuradas com SEDEX e PAC

![image](https://user-images.githubusercontent.com/4383507/67590344-310e7500-f731-11e9-91c6-c64f6907dbce.png)

WP e todos os plugins estão na última versão.

Logo só me faz pensar que o problema está no plugin Woocommerce Correios.

**Comment by claudiosanches** [comment]
Quem deve reconhecer a forma de entrega é o WooCommerce.
No caso isso geralmente é problema ou na sua configuração dos métodos de entrega ou na configuração das áreas de entrega.
Como esta configurado as áreas de entrega?
Ao ativar o log nos métodos de entrega, qual é a resposta dos Correios?

> Já fiz vários testes de incompatibilidade de plugins e o problema persiste.

Isso é perca de tempo, porque não tem nada que deve influenciar nisso, simplesmente funciona com o WooCommerce verificando a área de entrega que deve usar para o cliente e então o WooCommerce vai chamar os métodos de entrega dentro da área de entrega.
Se não aparece, é como eu falei, ou a área de entrega foi configurada errada ou os métodos de entrega tem dados invalidos e retorna erro da resposta dos Correios e por isso não mostra nada.

**Comment by andremomb** [comment]
Olá claudio boa noite!
Eu fiz a configuração da loja(endereços e tudo mais). Fiz também as medidas dos produtos, configurei a area de entrega e não aparece no meu site. Por acaso você pode me dar um auxilio ?

**Comment by bjrcarlos** [comment]
Eu consegui resolver observando os logs. Agora eu não me lembro qual era o erro. Pois faz algum tempo que resolvi.

Muito obrigado pela ajuda.

**Comment by andremomb** [comment]
@bjrcarlos  e @claudiosanches 
Eu percebi o que acontece, se o cara não clicar em calcular o frete ele não irá exibir porem o cara consegue prosseguir pra finalizar a compra.

Existe um modo de bloquear se o cara não calcular o frete não deixa ele prosseguir para finalizar a compra ?

**Comment by andremomb** [comment]
Outra coisa @bjrcarlos  

Como você fez pra traduzir essa mensagem **_"There are no shipping methods available. Please double check your address, or contact us if you need any help."_**

Eu instalei o Loco e ela já esta traduzido lá mais na pagina não aparece..
![image](https://user-images.githubusercontent.com/13700043/68720216-4dae0800-058d-11ea-9b4e-faaf3be07a40.png)

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
