### ISSUE TITLE
PHP Fatal error:  Cannot declare class WC_Correios_Tracking_Email

### ISSUE THREAD

**Issue by diegofcv** [claudiosanches/woocommerce-correios#172]
Olás,

Fui criar um usuário no WordPress (5.3) hoje, pelo painel administrativo, e recebi um erro de problemas no site. Fui na log e peguei o que segue:

[Tue Nov 26 22:34:50.223708 2019] [fcgid:warn] [pid 1304] [client xxx.xxx.xxx.xxx:35870] mod_fcgid: stderr: PHP Fatal error:  Cannot declare class WC_Correios_Tracking_Email, because the name is already in use in /var/www/xxxxxxxxx/wp-content/plugins/woocommerce-correios/includes/emails/class-wc-correios-tracking-email.php on line 0, referer: https://xxxxxxxx/wp-admin/user-new.php

Dei uma busca por aqui mas não achei nada. Alguém tem alguma ideia?

Ah, o usuário foi criado, apesar do erro. Mas obviamente, não é algo desejável que aconteça.

Abs, DiegoV

**Comment by henriquemattos** [comment]
@diegofcv, uma análise superficial apenas olhando para sua mensagem, parece que há mais de um plugin tentando inicializar o WooCommerce Correios. Sugiro que você verifique os plugins que tem ativado no site e que apenas o WooCommerce Correios inicie a classe WC_Correios_Tracking_Email.

Abraços e boa sorte.

**Comment by claudiosanches** [comment]
Funciona sem problemas na versão atual do plugin.
