### ISSUE TITLE
Máscara de CEP dentro de Minha conta

### ISSUE THREAD

**Issue by jofranlirio** [claudiosanches/woocommerce-correios#173]
Achei 2 situações onde a máscara de CEP não está sendo aplicada:

1) Entrega -> Opções de entrega - Quando no Woocommerce está com a opção marcada "Destino de entrega por padrão para o endereço de entrega do cliente" o segundo endereço no checkout não aplica a máscara.

2) Quando vamos editar o endereço de entrega ou cobrança dentro da área da conta do cliente, a máscara de CEP não é aplicada ao campo, permitindo letras. Ele até faz a consulta se eu coloco um CEP correto, mas sem a máscara, tudo é possível.

**Comment by claudiosanches** [comment]
Não esta ativada mesma nesta página, o plugin não tem função de formatar CEP pelo site inteiro.
