### ISSUE TITLE
Estado não é exibido ao carregar página de "Finalizar compra" quando opção "Forçar autopreenchimento" está habilitada

### ISSUE THREAD

**Issue by sangalli** [claudiosanches/woocommerce-correios#176]
Ao entrar na página de **Finalizar compra** (Checkout) com um usuário que já possui endereço cadastrado quando a opção **Forçar autopreenchimento** está selecionada nas configurações de integração com Woocommerce, a busca de endereço por CEP não consegue preencher o campo **Estado** do usuário, mesmo que já houvesse um estado cadastrado.

No comportamento atual, a função [fillFields](https://github.com/claudiosanches/woocommerce-correios/blob/09559dbb8c8f6b61449bfb7667023f021ded57d9/assets/js/frontend/autofill-address.js#L126-L128) faz com que o valor do campo Estado fique como **Selecione uma opção**.

Realizei alguns testes, e me parece se tratar de alguma incompatibilidade com a lib `select2`.

Fiz a seguinte alteração no código e resolveu o problema nos meus testes:

Substituição das linhas destacadas no arquivo [autofill-address.js](https://github.com/claudiosanches/woocommerce-correios/blob/09559dbb8c8f6b61449bfb7667023f021ded57d9/assets/js/frontend/autofill-address.js#L126-L128) pelo código a seguir:
```javascript
$( '#' + field + '_state' ).val( data.state ).change();
```

Se alguém que tem mais conhecimento do plugin puder me confirmar se esta solução é adequada, eu posso enviar um pull request da mudança.

**Comment by mariovalney** [comment]
Aqui também funcionou assim.

Enquanto não sai uma nova versão, você pode "forçar a barra" assim:
```
// Fix to autofill CEP problem
$( '#billing_state option, #shipping_postcode' ).on('change', function(event) {
  var value = this.value;

  if ( $(this).parent('select').val() === '' && value) {
    $(this).parent('select').val(value).change();
  }
});
```

**Comment by rfbastos** [comment]
Fiz as altreações mas nao rolou pra mim. O estado continua sem ser selecionado

**Comment by claudiosanches** [comment]
Corrigido nas versões atuais deste plugin.
