### ISSUE TITLE
Nenhum método de frete é retornado quando o valor do pedido está abaixo de 21.5

### ISSUE THREAD

**Issue by plovinicius** [claudiosanches/woocommerce-correios#178]
Olá, estou utilizando a última versão do **WooCommerce (4.0)** e a última versão do **WooCommerce Correios (3.8.0)** e estou tendo o seguinte problema:
- Quando tento fazer uma compra com um valor total abaixo de 21.5, ele não retorna nenhum método de frete disponível (tenho Sedex e PAC configurados);
- Caso aumente a quantidade de produtos para que o valor fique acima de 21.5 os frete são exibidos (então o cadastro dos produtos estão OK);
- Notei que no log ele retorna a seguinte mensagem: 
`[MsgErro] => Não foi encontrada precificação. ERP-013: Valor declarado nao permitido (valor minimo: 20,5, valor maximo: 10000)(-1).`

Sendo assim, o correto/ideal não seria o plugin verificar se o valor que está sendo enviado é menor do que o mínimo requerido pelos Correios, e se for ele enviar o valor mínimo para calcular o frete ?

**Comment by John-Henrique** [comment]
Desative a opção "valor declarado"

**Comment by 3m0** [comment]
O plugin faz esta verificação, mas creio que esteja desatualizado, pois está verificando com valor menor que R$: 18,00. Aumentando para o valor atual de R$: 20,50 resolveu o problema.

em shipping/class-wc-correios-shipping-<seumetododeentrega>.php

este trecho:
`protected function get_declared_value( $package ) {
	if ( 18 >= $package['contents_cost'] ) {
		return 0;
	}

	return $package['contents_cost'];
}`

muda para:
`protected function get_declared_value( $package ) {
	if ( 20.5 >= $package['contents_cost'] ) {
		return 0;
	}

	return $package['contents_cost'];
}`

**Comment by WesleyGoncalves** [comment]
Desativei a função "valor declarado" no método de entrega, como @John-Henrique sugeriu, e add o peso do produto. Depois disso funcionou.

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.

**Comment by jcpublish2024** [comment]
Bom dia Claudio.
Após atualizar o WebService, o frete não esta mais calculando o peso de todos os produtos quando aumento a quantidade de um único produto, exemplo1 produto do carrinho, frete R$ 10,00
10 produto no carrinho, frete continua os R$ 10,00
Pode me ajudar por favor, obrigado
