### ISSUE TITLE
Nenhuma opção de entrega foi encontrada: URL inválido

### ISSUE THREAD

**Issue by Matheuspombo** [claudiosanches/woocommerce-correios#180]
Alguem já teve este erro? o peso e dimensão do produto estão preenchidos.

04-02-2020 @ 20:10:42 - Weight and cubage of the order: Array
(
    [weight] => 0,13
    [height] => 2
    [width] => 11
    [length] => 16
)

04-02-2020 @ 20:10:42 - Requesting Correios WebServices: http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?nCdServico=04510&nCdEmpresa&sDsSenha&sCepDestino=88900033&sCepOrigem=01331020&nVlAltura=2&nVlLargura=11&nVlDiametro=0&nVlComprimento=16&nVlPeso=0,13&nCdFormato=1&sCdMaoPropria=N&nVlValorDeclarado=0&sCdAvisoRecebimento=N&StrRetorno=xml
04-02-2020 @ 20:10:44 - WP_Error: Não foi fornecido um URL válido.

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
