### ISSUE TITLE
link do código de rastreio na lista de pedidos parou de funcionar

### ISSUE THREAD

**Issue by ativadadigital** [claudiosanches/woocommerce-correios#181]
O link do código de rastreamento da lista de pedidos parou de funcionar, o mesmo está direcionando para a própria lista de pedidos quando clicado em cima.

Ele não direciona mais para a tela de rastreamento do correios, 
O comportamento do link dentro da página do pedido esta ok:

https://www2.correios.com.br/sistemas/rastreamento/resultado.cfm

Alguém sabe como corrigir essa situação?

**Comment by duca1010** [comment]
Vc vai precisar usar o link do SRO dos correios se não me engano.
esse link novo não puxa o rastreio.

no meu caso, eu configurei para o link abrir a página de rastreio nova (essa ai q vc postou) e o cliente cola o código qdo recebe no e-mail...

pq a tela do sro dos correios é meio feia

mas se vc quiser usar o sro..... o link fica assim:
http://www.websro.com.br/rastreamento-correios.php?P_COD_UNI=CÓDIGODERASTREIO

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
