### ISSUE TITLE
Filter de peso

### ISSUE THREAD

**Issue by andr3ribeiro** [claudiosanches/woocommerce-correios#183]
Olá!
Existe algum filter onde eu consiga ver se o peso é menor que 300g para forçar esse valor?
Peguei uma loja com esse problema do calculo que mostra o peso em um local do tema. Se eu mudar o peso pra calcular, a info da página vai ficar errada, queria tentar resolver isso sem adicionar um custom field e alterar o tema... ficar com 2 campos de peso.

Existe esse filter pra eu fazer uma condicional ??
Vlw!

**Comment by andr3ribeiro** [comment]
Pra quem tiver essa dúvida dei uma debugada e vi que isso é função do Woo fazer.

Encontrei uma solução:

add_filter( 'woocommerce_correios_shipping_args', 'min_peso_correios' );
function min_peso_correios( $args ) {
  $args['nVlPeso'] = $args['nVlPeso'] < 0.3 ? 0.3 : $args['nVlPeso'];
  return $args;
}

**Comment by brunomarks7** [comment]
Tive um problema agora com o peso quando atualizei o Woo, o WP e o plugin dos correios todos para última versão.

Aparentemente ele está mudando 0.200 kg para 200 kg, o que resulta em erro no retorno.

Exemplo:

`http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?nCdServico=04596&sCepDestino=76400000&sCepOrigem=11025250&nVlAltura=6&nVlLargura=11&nVlDiametro=0&nVlComprimento=16&nVlPeso=200,06&nCdFormato=1&sCdMaoPropria=N&nVlValorDeclarado=0&sCdAvisoRecebimento=N&StrRetorno=xml`

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
