### ISSUE TITLE
Problema com Estado

### ISSUE THREAD

**Issue by rfbastos** [claudiosanches/woocommerce-correios#184]
Ao digitar o cep, todo o endereço é preenchido, porém o estado não é selecionado.

**Comment by mmmontone** [comment]
Estou com o mesmo problema, o que pode ser?

**Comment by rfbastos** [comment]
Ainda sem solução aqui amigo. Mas acho que é problema com o select2

**Comment by marquimbanzai** [comment]
Funcionou Perfeitamente.. Obrigado!!! @rfbastos

**Comment by hugopc92** [comment]
Funcionou perfeitamente.

**Comment by jonasrafael** [comment]
Funcionou! Obrigado!

**Comment by rickdroio** [comment]
Caros, atualizei autofill-address.min.js com essa proposta, porém não ocorreu o preenchimento do campo estado. Sabem se é necessário atualizar o autofill-address.js também?
Em relação a versão oficial, existe algum candidato a release?
Abs

**Comment by rfbastos** [comment]
Pode tentar. Mas ja verificou se nao é o cache?

Cole aqui a URL do seu site com 

/wp-content/plugins/woocommerce-correios/assets/js/frontend/autofill-address.min.js

Assim confirmamos que está correto e analisamos outras situações

**Comment by dzieva** [comment]
Funcionou perfeitamente, muito obrigado!

**Comment by webnitech** [comment]
Obrigado pela sugestão da solução @rfbastos! @claudiosanches quando tiver disponibilidade e um tempo livre, dá uma olhadinha rápida nessa issue =)

**Comment by claudiosanches** [comment]
@rfbastos Por favor, envia um Pull Request.

**Comment by rfbastos** [comment]
Estimado @claudiosanches 

Fiz o Pull Request lá.

https://github.com/claudiosanches/woocommerce-correios/pull/200

Att

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
