### ISSUE TITLE
Valores de Carta Registrada desatualizados

### ISSUE THREAD

**Issue by sebrax** [claudiosanches/woocommerce-correios#186]
Olá! Verifiquei que os valores de carta registrada estão desatualizados. Acho que deveria usar pull request mas ainda não sei mexer muito bem com Git, então segue atualização da função `get_costs()`: _woocommerce-correios/includes/shipping/class-wc-correios-shipping-carta-registrada.php_ **linha 39**
```php
protected function get_costs() {
	return apply_filters( 'woocommerce_correios_carta_registrada_costs', array(
		'20'  => array(
			'R'     => 8.40,
			'AR'    => 14.75,
			'MP'    => 15.90,
			'AR+MP' => 22.25,
		),
		'50'  => array(
			'R'     => 9.20,
			'AR'    => 15.55,
			'MP'    => 16.70,
			'AR+MP' => 23.05,
		),
		'100' => array(
			'R'     => 10.30,
			'AR'    => 16.65,
			'MP'    => 17.80,
			'AR+MP' => 24.15,
		),
		'150' => array(
			'R'     => 11.15,
			'AR'    => 17.50,
			'MP'    => 18.65,
			'AR+MP' => 25.00,
		),
		'200' => array(
			'R'     => 12.00,
			'AR'    => 18.35,
			'MP'    => 19.50,
			'AR+MP' => 25.85,
		),
		'250' => array(
			'R'     => 12.90,
			'AR'    => 19.25,
			'MP'    => 20.40,
			'AR+MP' => 26.75,
		),
		'300' => array(
			'R'     => 13.85,
			'AR'    => 20.20,
			'MP'    => 21.35,
			'AR+MP' => 27.70,
		),
		'350' => array(
			'R'     => 14.70,
			'AR'    => 21.05,
			'MP'    => 22.20,
			'AR+MP' => 28.55,
		),
		'400' => array(
			'R'     => 15.60,
			'AR'    => 21.95,
			'MP'    => 23.10,
			'AR+MP' => 29.45,
		),
		'450' => array(
			'R'     => 16.45,
			'AR'    => 22.80,
			'MP'    => 23.95,
			'AR+MP' => 30.30,
		),
		'500' => array(
			'R'     => 17.35,
			'AR'    => 23.70,
			'MP'    => 24.85,
			'AR+MP' => 31.20,
		),
	), $this->id, $this->instance_id );
}
```

**Comment by henriquemattos** [comment]
@claudiosanches 

Eu não verifiquei os valores, apenas atualizei o código e criei o Pull Request (PR) para ajudar @sebrax e os mantainers do repositório. Não me responsabilizo pelo resultado pois faz tempo que não uso WordPress, WooCommerce e o plugin dos Correios.

Atenciosamente,
Henrique Mattos

**Comment by sebrax** [comment]
> @claudiosanches
> 
> Eu não verifiquei os valores, apenas atualizei o código e criei o Pull Request (PR) para ajudar @sebrax e os mantainers do repositório. Não me responsabilizo pelo resultado pois faz tempo que não uso WordPress, WooCommerce e o plugin dos Correios.
> 
> @sebrax, você poderia passar o link de referência de onde pegou esses valores para que eu possa atualizar também a documentação do arquivo fonte com o link correto?
> 
> Atenciosamente,
> Henrique Mattos

Opa, segue: https://www.correios.com.br/enviar-e-receber/correspondencia/carta/precos-e-prazos/carta

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
