### ISSUE TITLE
conflito com o woocommerce-pagarme

### ISSUE THREAD

**Issue by josefizuda** [claudiosanches/woocommerce-correios#188]
Não consigo gerar boleto ou finalizar uma venda no cartao com o plugin: Correios for WooCommerce VERSAO 3.8.0 ativado no meu site
ele aparece apenas uma tarjeta vermelha e nao finaliza
https://prnt.sc/stakgd

woocommerce 4.2.0
wordpress 5.4.1

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
