### ISSUE TITLE
Calculo no carrinho não funciona

### ISSUE THREAD

**Issue by leonardola** [claudiosanches/woocommerce-correios#189]
Ao tentar calcular o frete na pagina do carrinho recebo sempre a mensagem Nenhuma opção de entrega foi encontrada para ...
No checkout o calculo é feito corretamente. Caso eu faça o calculo no checkout e retorne para o carrinho o calculo aparece correto porém ao tentar atualiza-lo a mensagem de nenhuma opção de entrega foi encontrada retorna.

- Endereço da loja está configurado em Woocommerce > Configurações > Geral > Endereço da loja
- Max mind está configurado
- Localização padrão está como geolocate(tentei também todas as outras opções e geraram o aviso)
- Areas de entrega configuradas em WooCommerce > Configurações > Entrega ( Configurado para todo o brasil e também para todos os estados brasileiros)
- Cep padrão configurado em  WooCommerce > Configurações > Entrega > Brasil > Pac e Sedex
- Classe de entrega configurada como qualquer em  WooCommerce > Configurações > Entrega > Brasil > Pac e Sedex
- Logs ativos porém vazios
- Produto configurado com tamanho e peso maiores do que os valores mínimos configurados em WooCommerce > Configurações > Entrega > Brasil > Pac e Sedex
- Peso está configurado com a unidade correta (2kg e não 2 gramas)
- Todos os plugins foram desabilitados para teste porém o mesmo aviso aparece

Wordpress versão 5.4.1
Wocommerce versão 4.0.1
Plugin dos correios versão 3.8.0

notei que em wp-content/plugins/woocommerce-correios/includes/abstracts/class-wc-correios-shipping.php na linha 480
a variável $package['destination']['postcode'] está chegando vazia.

Também notei que em wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-cart.php na linha 42 o woocommerce ignora o set de billing location e shipping location por não ter um pais na requisição

**Comment by leonardola** [comment]
Durante alguns testes percebi que caso eu adicione um <input name="calc_shipping_country" value="BR"> no formulário utilizado para calculo de frete o frete é calculado corretamente

**Comment by leonardola** [comment]
adicionando o código abaixo no arquivo wp-content/themes/storefront/woocommerce/cart/shipping-calculator.php linha 29 corrige o problema. (Da forma como fiz não é necessário escolher o país pois o campo é hidden) 
```
<?php

                $country = WC()->customer->get_billing_country();

                if(!$country) {
                    $geo      = new WC_Geolocation(); // Get WC_Geolocation instance object
                    $user_ip  = $geo->get_ip_address(); // Get user IP
                    $user_geo = $geo->geolocate_ip( $user_ip ); // Get geolocated user data.
                    $country  = $user_geo['country']; // Get the country code
                }

                ?>

                <input name="calc_shipping_country" value="<?= $country ?>" hidden/>
```

**Comment by cjperes** [comment]
<input name="calc_shipping_country" value="BR" hidden/>

Perfeito, estava com o mesmo problema, adicionei o input acima e o frete voltou a funcionar.

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
