### ISSUE TITLE
Melhoria no calculo para produtos pequenos.

### ISSUE THREAD

**Issue by Nihaum** [claudiosanches/woocommerce-correios#191]
Olá!

*** EDIT

O problema que deu agora foi com o valor declarado. Tem como desligar o valor declarado quando for menor que os 20,50?

Obrigado!

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
