### ISSUE TITLE
Registro Módico

### ISSUE THREAD

**Issue by castrocv** [claudiosanches/woocommerce-correios#193]
Boa tarde,

Parabéns pelo plugin, excelente

acabei de reinstalar o plugin em oficiodaspalavras.com.br, que é uma editora de livros, porém não tem mais o  REGISTRO MÓDICO - (Livros de maneira geral, postados por qualquer pessoa física ou jurídica, e Material Didático em geral postado por Escola de Ensino por correspondência e destinados a seus alunos) é isso mesmo?

Grato

**Comment by mmvestudio** [comment]
Olá! 
Aproveitando o título...
Primeiramente informo que essa opção está em editar no método de entrega.
Porém no meu caso, no site livroslegais.com.br o valor calculado para envio de registro módico fica sempre em 4 reais. Independente do peso do livro.
Será que tem algum problema no plugin ou algum detalhe na configuração que não percebi?

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
