### ISSUE TITLE
O campo de Estado não pode ser alterado por alguns clientes.

### ISSUE THREAD

**Issue by felipembraga** [claudiosanches/woocommerce-correios#195]
Oi, já tentei replicar esse problema e não consigo, mas muito clientes reclamam que após incluirem o CEP no checkout, os dados são preenchidos automativamente mas não o Estado, e o mesmo não pode ser alterado manualmente.

Hoje um usuário usando iPhone com Safari teve esse problema.

**Comment by khigashi** [comment]
Todos os dias tenho problemas com clientes com esse problema e não consigo reproduzir também. Desativei o preenchimento automático, menos conveniente mas acredito que vá resolver.

**Comment by jonasrafael** [comment]
Salve Claudio, tudo certo?

Na recente atualização do Woocommerce o campo “estado” (billing_state) deixou de ser auto-preenchido depois de colocar o CEP. A cidade, a rua continuam sendo preenchidos normalmentes.

Já tentei:
– Desativar todos os plugins;
– Mudar de tema;

Log:
08-31-2020 @ 10:27:10 – Fetching address for “85501020” on Correios Webservices…
08-31-2020 @ 10:27:13 – Address for “85501020” found successfully: stdClass Object
(
[postcode] => 85501020
[address] => Rua Goianases
[city] => Pato Branco
[neighborhood] => Centro
[state] => PR
[last_query] => 2020-08-31 10:27:13
)

**Comment by jonasrafael** [comment]
Essa solução funcionou: https://github.com/claudiosanches/woocommerce-correios/issues/184

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
