### ISSUE TITLE
Problema quando o valor da compra é inferior ao Valor Declarado Mínimo aceito pelos Correios

### ISSUE THREAD

**Issue by raulvinicius** [claudiosanches/woocommerce-correios#196]
O formulário de cálculo do frete retorna "Nenhuma opção de entrega foi encontrada" quando o valor da compra é inferior à R$20,50 que, atualmente, é o valor mínimo que o Correios aceita para ser declarado.

O problema ocorreu com uma venda de um cliente e, enquanto eu contornava a situação, fui no site dos Correios para calcular o frete "manualmente" e recebi o erro "(-1) - ERP-013: Vlr declarado nao permitido, aceito entre R$ 20,50 e R$ 3000,00.". 

Então eu coloquei o valor do produto em questão por R$21 (estava por R$20) e tudo voltou a funcionar normalmente.

**Comment by ChicoCybergoth** [comment]
Estou tendo essa questão também.

**Comment by olabertolino** [comment]
Estou tendo o mesmo problema. Porém é só um range de valores que não aceita... De R$18,xx até R$20,xx. Abaixo de R$18 está funcionando normal o frete e acima de R$21 também. É só nesse range que estou enfrentando esse bug de não achar frete disponível. Se alguém puder me ajudar! OBRIGADO!

**Comment by ChicoCybergoth** [comment]
@olabertolino
Sim, é bem isso mesmo, estou passando pelo mesmo problema, estou contornando dessa forma aqui embora ache que não seja uma boa prática está funcionando.

Trocar essa parte em:
woocommerce-correios/includes/class-wc-correios-webservice.php
`
	/**
	 * Set declared value.
	 *
	 * @param string $declared_value Declared value.
	 */
	public function set_declared_value( $declared_value = '0' ) {
		//$this->declared_value = $declared_value;
		$this->declared_value = ($declared_value<22) ? 22 : $declared_value;
	}
`

**Comment by olabertolino** [comment]
Folks, consegui resolver o problema de uma forma mais simples:
Basta acessar Woocommerce > Configurações > Entrega > Brasil > PAC > editar
Desmarcar a opção ***Declarar valor para seguro*** e pronto! Vai funcionar!

Fazer isso com os demais tipos de frete dos correios que funcionará. Pelo entendi o valor calculado do seguro que dá esse bug. 

Espero que ajudem vocês!

**Comment by ChicoCybergoth** [comment]
@olabertolino , cara, se você fizer isso o módulo não vai calcular o seguro, se mandar com seguro o valor será mais alto que o cobrado do comprador (você terá que pagar do seu bolso) ou terá que enviar sem o seguro, contando somente com a sorte, caso aconteça algo com a encomenda você receberá somente o seguro automático, que se não me engano é R$20,00.
Os Correios são excelentes em criar problema para vender solução, igual o governo...

**Comment by henrikcozza** [comment]
A solução é simples, basta ajustar a constante de valor minimo para calculo de seguro que atualmente esta em 18 reais, ultima vez atualizado em 2017, para 20,50, o erro acontece entre 19,01 a 20,49, que é a API dos correios regeitando valores abaixo de 20,50.

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
