### ISSUE TITLE
Preço do plugin e diferente do preço fornecido pelos correios

### ISSUE THREAD

**Issue by alvarofiore** [claudiosanches/woocommerce-correios#197]
Olá! Estou fazendo um teste de compra de um produto da pagina daterraquecura.com Quando escolho Sedex, do CEP origen:18325000 ao CEP destino:38050040 com um peso de 0.3kg e dimensões 8x23x15 na pagina dos correios o orçamento fica em R$55 mas na nossa loja com o plugin o orçamento é R$27. Porque tem tanta diferença? as configurações são as mesmas.

**Comment by rfbastos** [comment]
A url do plugin é a abaixo. 


A consulta é direto no site dos correios.

Possivelmente há uma divergencia entre os dados que vc colocou no site dos correios e no seu site.


**PAC SEM CONTRATO - 04510**
http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?nCdServico=04510&nCdEmpresa=&sDsSenha=&sCepDestino=38050040&sCepOrigem=18325000&nVlAltura=8&nVlLargura=23&nVlDiametro=0&nVlComprimento=15&nVlPeso=0,3&nCdFormato=1&sCdMaoPropria=N&nVlValorDeclarado=0&sCdAvisoRecebimento=N&StrRetorno=xml

**SEDEX SEM CONTRATO - 40010**

http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?nCdServico=40010&nCdEmpresa=&sDsSenha=&sCepDestino=38050040&sCepOrigem=18325000&nVlAltura=8&nVlLargura=23&nVlDiametro=0&nVlComprimento=15&nVlPeso=0,3&nCdFormato=1&sCdMaoPropria=N&nVlValorDeclarado=0&sCdAvisoRecebimento=N&StrRetorno=xml

<Servicos>
<cServico>
<Codigo>40010</Codigo>
**<Valor>55,60</Valor>**
<PrazoEntrega>5</PrazoEntrega>
<ValorSemAdicionais>55,60</ValorSemAdicionais>
<ValorMaoPropria>0,00</ValorMaoPropria>
<ValorAvisoRecebimento>0,00</ValorAvisoRecebimento>
<ValorValorDeclarado>0,00</ValorValorDeclarado>
<EntregaDomiciliar>S</EntregaDomiciliar>
<EntregaSabado>S</EntregaSabado>
<obsFim/>
<Erro>0</Erro>
<MsgErro/>
</cServico>
</Servicos>

Com certeza tem algo no seu site não configurado. 

Habilite o LOG e cole aqui, caso ainda precise de ajuda

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
