### ISSUE TITLE
Adicionar código de rastreio no pedido não funciona

### ISSUE THREAD

**Issue by VictorAragon** [claudiosanches/woocommerce-correios#198]
Olá, bom dia.
Nos pedidos, no campo de adicionar código de rastreio, ao colocar o código e clicar no "+" nada acontece. Não envia nenhuma ação, não gera nenhuma movimentação, nada.

Consequentemente não é enviado o e-mail para os clientes com o rastreio do pedido dos mesmos.

PS: Wordpress versão 5.5.1, WooCommerce versão 4.0.1 e 4.5.2 (testei em ambos e nenhum funciona).

**Comment by CasperBraske** [comment]
Provavelmente é uma incompatibilidade com algum plug-in ou o tema.
Veja no console do navegador se não existem erros de JavaScript.

**Comment by vinimarcili** [comment]
Estou com o mesmo problema, o console não exibe nenhum erro diferente do normal

**Comment by claudiosanches** [comment]
Funcionando sem problema na versão atual do plugin.
