### ISSUE TITLE
Error 225: Customer Address District is Required

### ISSUE THREAD

**Issue by RPellegrinelli** [claudiosanches/woocommerce-correios#203]
O Erro acontece quando alguns CEPs são utilizados, normalmente cidades pequenas que são CEP único, 
o campo Rua fica em branco e o usuario nao consegue preencher, se o cliente tenta proceder com o pagamento o sistema gera um pedido com status PAGAMENTO PENDENTE.

Dois exemplos abaixo:
15890-000
15640-000

![Screenshot 2020-11-30 at 19 16 41](https://user-images.githubusercontent.com/75280581/100672370-9d9a7100-3340-11eb-92e9-3456bf0c5d90.png)

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
