### ISSUE TITLE
Opções de entrega não são atualizadas quando CEP é alterado na página de "Finalizar compra" quando opção "Forçar autopreenchimento" está habilitada

### ISSUE THREAD

**Issue by rosinaldobsb** [claudiosanches/woocommerce-correios#204]
Sou usuário do plugin para WooCommerce do PagSeguro e do WooCommerce Correios feitos pelo Claudio Sanches.

Na tela do carrinho, quando o usuário clica em "Calcular entrega", ele informa lá:
Estado
Cidade
CEP

E em seguida ele clica em Concluir compra e é redirecionado para a página de Finalizar compra (Checkout).

Ao entrar na página de Finalizar compra (Checkout) os dados do PagSeguro nos campos da esquerda são preenchidos automaticamente e isso é ótimo:
CEP
Endereço
Bairro
Cidade
Estado

E nesta mesma página no lado direito, acima das opções de pagamento do PagSeguro, aparecem as mesmas opções de entrega e a opção selecionada na tela do Carrinho de onde o usuário veio. E isso também é muito bom.

Quando a opção Forçar autopreenchimento está selecionada nas configurações de integração com Woocommerce do plugin do WooCommerce Correios, se o usuário resolver trocar o CEP na página de finalização de compra, a busca pelo endereço é realizada e os campos de Endereço no lado esquerdo da tela são atualizados perfeitamente. E isso também é muito bom.

**O PROBLEMA:**

A alteração do CEP não causa a atualização das opções de entrega que ficam no lado direito acima das opções de pagamento do PagSeguro.

Peço que seja corrigido isso para que a pessoa possa selecionar outra opção de entrega, caso ela altere o CEP na página de finalização da compra do PagSeguro.

Muito obrigado.

PS: não sou desenvolvedor. Aguardo uma solução de quem possa atualizar o plugin. Se puderem votar nesse pedido para chamar a atenção deste problema, agradeço muito.

**Comment by davisonajr** [comment]
Eu tenho o mesmo problema e ele ocorre principalmente no Chrome.
Nos meus testes no Mozilla funciona até que ok, as vezes não completa automático mas na maioria das vezes sim. O registro do log também aponta que a requisição no API foi bem sucedida.

Agora, no Chrome, nada acontece mesmo... nem mesmo há registro de erros no Inspetor do navegador.
Por favor, alguém nos ajude.

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
