### ISSUE TITLE
Fretes com custos diferentes p/ produtos com as mesmas dimensões e peso.

### ISSUE THREAD

**Issue by Brunojsza** [claudiosanches/woocommerce-correios#206]
Quando eu calculo o frete para produtos com as mesmas dimensões e peso, porém, com preços diferentes, o custo de frete também altera. O que não faz sentido, uma vez que o cálculo é feito baseado apenas no peso e dimensão do produto. Alguém mais tem esse problema?

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
