### ISSUE TITLE
Não funciona na nova versão do woocommerce

### ISSUE THREAD

**Issue by artutava** [claudiosanches/woocommerce-correios#207]
Não está funcionando o cálculo de frente para o Brasil. Alguns dias atrás estava funcionando. Talvez tenha sido algum update do woocommerce.

**Comment by mvldebian** [comment]
Estou com problema na versão atual, acredito que configurei tudo corretamente inclusive adicionei peso e medidas nos produtos, mas não carrega nada na pagina do carrinho somente retirada no local... wordpress e woocommerce nas ultimas versões

**Comment by claudiosanches** [comment]
Funciona sem problemas na versão atual do WooCommerce.
