### ISSUE TITLE
Dúvida sobre Dificuldade em selecionar campo estado com autocomplete no iphone ios

### ISSUE THREAD

**Issue by seomartin** [claudiosanches/woocommerce-correios#210]
Identifiquei através de 3 clientes distintos em gravações de tela um problema que ocorre somente no iphone com a função de autocomplete ativada no plugin. Desativei plugins e temas diferentes e o comportamento é igual, será que deixei passar algo?

>> Após inserir os dados de cep e número, não seleciona o estado corretamente e para que isso ocorra é necessário selecionar outro estado e depois o estado correto, ou seja, o autocomplete não funciona e impacta um pouco a usabilidade do checkout. mantive sem autocomplete e está funcionando por enquanto. 

Segue vídeo explicativo no link: https://teste.seomartin.com/wp-content/uploads/2021/02/waufen-correios-woo-autocomplete-issue-2302212213.mp4

**Comment by gbaims** [comment]
Também estou passando pelo mesmo problema. @seomartin conseguiu encontrar alguma solução?

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.

**Comment by seomartin** [comment]
valew claudio
