### ISSUE TITLE
Feedback do Prazo de Entrega

### ISSUE THREAD

**Issue by rfsouzax** [claudiosanches/woocommerce-correios#211]
Olá, 
Estou com um problema em relação ao que está aparecendo para o cliente, no e-mail de confirmação da compra, que segue da seguinte forma na tabela do frete:
 
_(entrega dentro de X dias úteis, após o pagamento)_ 

Porém, como o prazo dos correios é estimado, isso vem gerando inúmeros problemas, sendo assim, minha sugestão é que seria melhor se estivesse da seguinte forma:

_(entrega **estimada** dentro de X dias úteis, após o **envio**)_
 
Por acaso seria possível eu alterar este texto em algum lugar no plugin, ou é somente via atualização do plugin mesmo?

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
