### ISSUE TITLE
Pedido sendo concluído sem frete selecionado

### ISSUE THREAD

**Issue by fuba182** [claudiosanches/woocommerce-correios#218]
Percebemos em 2 sites diferentes com um fluxo considerável de acessos e compras que, pedidos estão sendo registrados sem método de frete escolhido. E isto não se dá aleatoriamente, ocorre sempre quando há algum erro de consulta ao web service:

2 exemplos de erros que acarretaram em pedido gerado sem frete: 

1 - WP_Error: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received
2 - [Erro] => -888
[MsgErro] => Não foi encontrada precificação. The remote server returned an error: (504) Gateway Timeout.

Quando não tem problemas na consulta ao webservice, aparentemente não tem problemas na geração do pedido. Porém se tem problemas de consulta o erro acontece. Isto é realmente sério pois de maneira alguma poderia ser permitido registrar um pedido sem método de envio quando se tem um.

Podem nos ajudar. Obrigado.

**Comment by gutobenn** [comment]
@fuba182 Nesses casos que você falou, a pessoa não chega a ver nenhuma modalidade de frete?

Tem um problema que vejo acontecer há alguns anos em uma instalação que tem um tráfego muito alto durante um curto período. Para o cliente aparece a opção de frete e ele consegue selecionar, mas ao finalizar o pedido o frete não é registrado (e nem ele é cobrado por isso). É o mesmo caso que o seu ou não?

**Comment by fuba182** [comment]
@gutobenn sim... o mesmo caso... o cliente seleciona a modalidade de frete.
Vemos pelo log que mostra a consulta retornou valor de frete alguns segundos antes de finalizar a compra.
Porém o que parece é que ao clicar no botão finalizar compra ele consulta novamente e o webservice retorna erro e o cliente consegue finalizar a compra.

Sim temos muito tráfego e acontece a muito tempo, recentemente aconteceu em 5 pedidos em um dia, o suficiente para trocar de plugin pois este não encontramos mais suporte.

Vejo como gravíssimo o cliente poder finalizar uma compra sem frete. Prejuízo direto.

Obs: Utilizamos contrato dos correios, em 3 sites que gerenciamos já aconteceu o problema, ambos com tráfego alto, e com objetivos e plugins diferentes.

**Comment by gutobenn** [comment]
@fuba182 Caramba, que bom encontrar mais alguém para conversar sobre esse problema! 

Qual plugin vocês estão utilizando agora?

Valeu por responder tão rápido!

**Comment by gutobenn** [comment]
@fuba182 Aqui esse problema tem acontecido em 0,75% dos pedidos, e inclusive com a modalidade Impresso Normal, que nem usa o webservice dos Correios. É um percentual bem alto.

Eu estava com os logs do plugin desabilitados em produção, mas ativei agora para ver se consigo ver alguma requisição retornando erro, assim como você falou no primeiro post.

@claudiosanches você tem alguma ideia do que pode ser? Eu tenho disponibilidade de tempo e uma certa urgência para tentar resolver esse problema, então posso dedicar algum tempo hoje e nos próximos dias a isso. Mas não estou sabendo muito bem onde pode estar o problema.

**Comment by fuba182** [comment]
olá @gutobenn ... enviei um email para o endereço que consta em seu perfil...

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
