### ISSUE TITLE
valor do frete errado

### ISSUE THREAD

**Issue by ezequieldiaz29** [claudiosanches/woocommerce-correios#219]
o valor do frete esta bem superior ao valor cobrado pela calculadora do site oficial dos correios,  37,10 X 27,40. Como posso resolver isso?

**Comment by silvaalanchristian** [comment]
Quais as dimensões e peso do produto?

Verifique se está em kg ou g e centímetro ou metro as unidades de peso e medidas, respectivamente.

**Comment by jacquecohen** [comment]
O valor do frete está desatualizado. Terá atualização?

**Comment by ezequieldiaz29** [comment]
era algum problema na configuração nos produtos compostos
