### ISSUE TITLE
Problema: Não existem métodos de entrega disponíveis

### ISSUE THREAD

**Issue by jajacaraujo** [claudiosanches/woocommerce-correios#220]
Ta tudo configurado direitinho, mas na hora de finalizar , essa mensagem não sai, sendo que o PAC e o SEDEX ta configurado direito assim como os atributos dos produtos.
Tem jeito?

**Comment by saul0kz** [comment]
comigo isso acontece quando não preencho as dimensões do produto corretamente.

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
