### ISSUE TITLE
Método de envio não aparece na hora do checkout

### ISSUE THREAD

**Issue by arin-nora** [claudiosanches/woocommerce-correios#222]
Adicionei as opções PAC e Impresso Normal para os envios no meu site, porém apenas PAC aparece na hora de finalizar a compra. O que aconteceu?

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
