### ISSUE TITLE
Auto Fill Address on Products Page/Woocommerce Shipping Calculator On Product Page

### ISSUE THREAD

**Issue by AcuriosNab** [claudiosanches/woocommerce-correios#223]
Olá, eu preciso que o auto preenchimento tbm funcione na página de produto. Pra isso, eu gostaria de saber se há algum meio rápido. Ex: colocar as classes e/ou ids dos campos de endereço como os do formulário no checkout (Isso eu fiz, porém não funconou), e se incluir algum script na página de produto tbm. O plugin que calcula o frete na página do produto é o Woocommerce Shipping Calculator On Product Page. Ele faz um bom trabalho, porém eu gostaria de incrementar com o auto preenchimento.  Se existir algum outro meio pra mostrar os meios de entrega disponiveis e os respectivos preços eu tbm sou todo ouvidos (Ou olhos kkkk)

Eu não sei e é aqui que devo postar isso. Qualquer direcionamento e/ou ajuda eu agradeço muito galera.

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
