### ISSUE TITLE
Erro Fatal

### ISSUE THREAD

**Issue by Karinenegri** [claudiosanches/woocommerce-correios#224]
Bom dia, 
Depois que instalei o plugin não consigo mais acessar o painel do wordpress.

Erro fatal: ArgumentCountError não capturado: poucos argumentos para a função CFPP \ {closure} (), 1 aprovado em /home/serrano23chocola/public_html/wp-includes/class-wp-hook.php na linha 286 e exatamente 2 esperados em / home /serrano23chocola/public_html/wp-content/plugins/woo-correios-calculo-de-frete-na-pagina-do-produto/woo-correios-calculo-de-frete-na-pagina-do-produto.php:60 Rastreamento de pilha: # 0 /home/serrano23chocola/public_html/wp-includes/class-wp-hook.php(286): CFPP \ {closure} (5) # 1 / home / serrano23chocola / public_html / wp-includes / plugin. php (203): WP_Hook-> apply_filters (5, Array) # 2 /home/serrano23chocola/public_html/wp-includes/class-http.php(158): apply_filters ('http_request_ti ...', 5) # 3 / home / serrano23chocola / public_html / wp-includes / class-http.php (606): WP_Http-> request ('http: //api.muff ...',Array) # 4 /home/serrano23chocola/public_html/wp-includes/http.php(170): WP_Http-> get ('http: //api.muff ...', Array) # 5 / home / serrano23chocola / public_html /wp-content/themes/betheme/functions/admin/class-mfn-api.php(81): wp_remote_get ('http: //api.m in / home / serrano23chocola / public_html / wp-content / plugins / woo- correios-calculo-de-frete-na-pagina-do-produto / woo-correios-calculo-de-frete-na-pagina-do-produto.php na linha 60

o que devo fazer?

**Comment by claudiosanches** [comment]
Esse plugin que você esta utiliznaod não é este daqui, parece ser outro plugin, este plugin não se chama "woo- correios-calculo-de-frete-na-pagina-do-produto"
