### ISSUE TITLE
Usando a classe WC_Correios_Webservice para fazer consultas programáticas

### ISSUE THREAD

**Issue by brasofilo** [claudiosanches/woocommerce-correios#225]
Olá!
Ainda não tive oportunidade de fazer testes mas já aproveito para expor a idéia caso alguém possa contribuir.

Preciso fazer um levantamento de custos de SEDEX, com diferentes pesos, para uma lista de CEPs.
Dá pra fazer manualmente? Sim, dá.

Mas claro que...

![image](https://user-images.githubusercontent.com/1542052/140245619-2f70ca8b-15f0-4054-8535-afdbfcdecf39.png)

Vou tentar fazer como este método na classe `WC_Correios_Shipping`, minha única dúvida por enquanto é se o `$this->id` é necessário... A classe `WC_Correios_Shipping_Legacy` chama o Webservice sem `instance_id`, mas acho que o `id` também é opcional...

	protected function get_rate( $package ) {
		$api = new WC_Correios_Webservice( $this->id, $this->instance_id );
		$api->set_debug( $this->debug );
		$api->set_service( $this->get_code() );
		$api->set_package( $package );
		$api->set_origin_postcode( $this->origin_postcode );
		$api->set_destination_postcode( $package['destination']['postcode'] );

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
