### ISSUE TITLE
Cálculo do valor de entrega incorreto quando adicionado uma quantidade maior de produtos.

### ISSUE THREAD

**Issue by StefanySantogo** [claudiosanches/woocommerce-correios#226]
Estou usando os plugin woocomerce, e correios (Claudio sanches) e 
woocommerce-shipping-calculator-in-product.
O cálculo está com uma diferença de mais do que o dobro no valor de entrega, quando é incluído uma grande quantidade de produtos. São produtos para abastecer papelarias então sempre vende acima de 100 unidades e o plugin calcula separadamente a embalagem, isso leva o valor nas alturas. O que deve ser feito e configurado pra que o plugin calcule o produto somando apenas suas medidas e seu peso como é feito no site dos correios?  Bom ressaltando que em pouca quantidade o valor é calculado corretamente.

**Comment by Samylascarlet** [comment]
comigo está acontecendo o mesmo, você já conseguiu solucionar?

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
