### ISSUE TITLE
[Erro] -888

### ISSUE THREAD

**Issue by Samylascarlet** [claudiosanches/woocommerce-correios#227]
Dimensões estão ok, cep está ok, mas o valor do frete esta dando um valor exorbitante e não aparece a opção Pac e Sedex em alguns produtos

[Codigo] => 04014
            [Valor] => 0,00
            [PrazoEntrega] => 0
            [ValorSemAdicionais] => 0,00
            [ValorMaoPropria] => 0,00
            [ValorAvisoRecebimento] => 0,00
            [ValorValorDeclarado] => 0,00
            [EntregaDomiciliar] => SimpleXMLElement Object
                (
                )

            [EntregaSabado] => SimpleXMLElement Object
                (
                )

            [obsFim] => SimpleXMLElement Object
                (
                )

            [Erro] => -888
            [MsgErro] => Não foi encontrada precificação. ERP-013: Vlr declarado nao permitido, aceito entre R$ 21,00 e R$ 10000,00(-1).

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
