### ISSUE TITLE
Valor do frete muito mais alto [dimensões das peças em tamanho normal]

### ISSUE THREAD

**Issue by Samylascarlet** [claudiosanches/woocommerce-correios#228]
![WhatsApp Image 2021-11-19 at 16 46 30](https://user-images.githubusercontent.com/94712785/142682961-5dbdd5ed-ab0e-4fe6-89d4-d7dd2cce0300.jpeg)

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
