### ISSUE TITLE
Erro nas medidas

### ISSUE THREAD

**Issue by HimorriveL** [claudiosanches/woocommerce-correios#240]
Produto foi cadastrado com esses dados:

![image](https://user-images.githubusercontent.com/60895471/191765496-d8163b55-68e1-4947-85f7-efe6917e5e22.png)

porém no envio do webservice está sendo enviado:

![image](https://user-images.githubusercontent.com/60895471/191765717-33b4b893-5458-422b-8ea6-15f9f130003d.png)

observe que foi cadastrado as medidas como 22x44x33 porém está sendo enviado como 26,9x44x26,9

**Comment by claudiosanches** [comment]
Fechando já que o Webservice antigo não é mais suportado por este plugin, se ainda tiver algum problema com a versão atual do plugin, por favor crie um tópico novo.
