### ISSUE TITLE
Nova API dos Correios

### ISSUE THREAD

**Issue by sebrax** [claudiosanches/woocommerce-correios#241]
Meus caros, acredito que esse plugin tenha sido descontinuado mas os Correios anunciaram o prazo para clientes de contrato utilizarem as novas APIs até 30/09/2022. Não sei se o webservice que utilizamos continuará funcionando mas temos alguma solução para isso?

Sou muito grato por esse plugin e ele tem me atendido até então mas como tive de criar vários hooks/filters para se adequar, se for o caso de desenvolver algo novo, migrarei pro Magento.

[Documentação da nova API dos Correios](https://www.correios.com.br/atendimento/developers/correios-developers)

**Comment by claudiosanches** [comment]
Já implementando na versão 4.0.
