### ISSUE TITLE
Leve internacional não funciona mais

### ISSUE THREAD

**Issue by juanp00** [claudiosanches/woocommerce-correios#247]
Olá, meu cliente possuí os serviços de envio internacional do correio, inseri o codigo e senha administrativa mas não é realizado o calculo no leve internacional e no log recebo o seguinte erro: 
03-30-2023 @ 17:00:25 - Weight and cubage of the order: Array
(
    [weight] => 6816
    [height] => 95
    [width] => 95
    [length] => 240
)

03-30-2023 @ 17:00:25 - Requesting Correios WebServices: http://www2.correios.com.br/sistemas/efi/bb/Consulta.cfm?tipoConsulta=Geral&especif=209&uforigem=AC&localidade=C&pais=PT&altura=95&largura=95&profundidade=240&peso=6816&reset=true
03-30-2023 @ 17:00:26 - Correios WebServices response: SimpleXMLElement Object
(
    [versao_arquivo] => 1.0
    [tipo_servico] => 45000
    [erro] => SimpleXMLElement Object
        (
            [codigo] => 16
            [descricao] => A consulta não está mais disponível, favor acessar o novo componente "Precificação Rest - Internacional" nos Correios Web Services https://apps.correios.com.br/componentes/.
        )

)

Pela mensagem entendi que esse método de consulta não está mais funcionando, se realmente for somente isso, tem previsão para incluir o novo método de consulta? 
Não encontrei nenhum plugin semelhante que faca essa consulta internacional, seria de grande ajuda!!

**Comment by sebosfato** [comment]
Conseguiu uma solução?

**Comment by juanp00** [comment]
> Conseguiu uma solução?

Ainda não :/

**Comment by claudiosanches** [comment]
Os Correios desativou a API antiga, precisa de uma integração nova para isso.
