### ISSUE TITLE
Carrinho 

### ISSUE THREAD

**Issue by SucreLee3** [claudiosanches/woocommerce-correios#248]
Olá, não sei se esse problema se encaixa exatamente aqui, mas perguntarei de todo modo. Utilizo o plugin e, acredito que seja ele, que coloca, na página do carrinho, o cálculo do frete. No entanto, eu gostaria que a única informação que o cliente tivesse que preencher fosse seu cep, não o país, estado, cidade e cep. Sabe me ajudar? Desde já agradeço.
![image](https://github.com/claudiosanches/woocommerce-correios/assets/133133613/a191c0be-953e-4544-a712-c9189cb045fc)

**Comment by luiseduardobraschi** [comment]
Quem coloca a calculadora na página do carrinho é o próprio WooCommerce.

Segue um plug-in pra te ajudar no que você precisa:

https://wordpress.org/plugins/woo-better-shipping-calculator-for-brazil/

Obs.: Issues do GitHub são para problemas relacionados ao código do plug-in então não é o lugar mais adequado pra fazer esse tipo de solicitação.
