### ISSUE TITLE
Novos ambientes de API’s para obtenção de informações de preços, prazos e rastreamento

### ISSUE THREAD

**Issue by relderdesigner** [claudiosanches/woocommerce-correios#251]
Pessoal, boa tarde, recebi esse e-mail dos correios, alguem sabe me informar se mudará algo no plugin?

Prezado(a) Cliente,

     Alinhado ao compromisso de oferecer as melhores soluções aos nossos Clientes, em meados do primeiro semestre de 2022 os Correios disponibilizaram novos ambientes de API’s (Application Programming Interface) para obtenção de informações de preços, prazos e rastreamento. Essas, desenvolvidas em arquitetura (REST), trazem inúmeras vantagens aos usuários, tais como maior segurança, menor tempo de resposta, ambiente escalável, novo e totalmente aderente às principais tecnologias do mercado.

     Nesse interim, trabalhamos junto às principais plataformas fornecedoras de tecnologia para e-commerce para que integrassem suas aplicações às novas API’s disponibilizadas pelos Correios, visando cumprir os prazos para desativação da antiga estrutura que fornecia esses serviços.

     Nesse contexto, informamos que os antigos ambientes de cálculo de preços e prazos (API SOAP) serão desativados em 01/09/2023. Sendo assim, recomendamos que verifique junto à sua área de TI e/ou plataforma integradora/ERP/TMS se já estão integrados aos novos ambientes dos Correios e, caso ainda não estejam, pedimos acionar o Consultor Comercial, Agência de Relacionamento responsável pelo seu Contrato, e se for o caso, nossa CAC – Central de Atendimento.

     Ressaltamos que todos os Clientes detentores de Contrato a partir do pacote Bronze já tem acesso liberado às novas API’s, porém é necessário que criem credenciais no ambiente [Meu Correios](https://meucorreios.correios.com.br/app/index.php) e emitam a senha de consumo de API’s no Correios [Web Service](https://cws.correios.com.br/), condições exigidas para consumo das novas API’s.

     Vale destacar ainda que cada plataforma adota procedimentos específicos para uso desse novo modelo de integração, de modo que recomendamos verificar tais procedimentos junto à sua plataforma.

     Contate o seu Consultor Comercial, Agência de Relacionamento dos Correios, e se for o caso, nossa CAC – Central de Atendimento, para esclarecimentos adicionais ou acesse: https://www.correios.com.br/atendimento/developers/correios-developers.

Cordialmente,
Empresa Brasileira de Correios e Telégrafos.

**Comment by claudiosanches** [comment]
Já integrado na versão 4.0.
