### ISSUE TITLE
Adicionar suporte para classes de entrega para todos os métodos.

### ISSUE THREAD

**Issue by claudiosanches** [claudiosanches/woocommerce-correios#55]
Baseado neste comentário:

https://wordpress.org/support/topic/metodos-de-entrega-configura-los-por-produto/#post-7660660

> Seria possível ativar a opção de classe de entrega da carta registrada para outros métodos de entrega, como PAC e SEDEX? A complexidade de alteração no código seria baixa, eu presumo, e com isso naturalmente seria possível definir opções de fretes diferenciados, por produto, CEP de origem etc, configurando as áreas do Woocommerce.
> 
> Tenho produtos que necessitam tratamento diferenciado (que as classes de entrega da carta registrada atenderiam como uma luva) mas que não posso enviar por carta registrada por não se adequarem nas dimensões.

Consigo ver alguns "user cases" para isso, já que seria possível cobrar taxas diferentes de manuseio e também configurar estimativas diferentes de entrega para cada classe.

**Comment by gbvaz** [comment]
Cheguei aqui procurando exatamente por esta solução. Vi que no tópico de suporte do wordpress referenciado também há interesse nessa evolução. Meu caso é que preciso utilizar classes de envio para diferentes produtos, mas ainda sim usar PAC, SEDEX, eSEDEX etc. com CEP's de origem diferentes, para suprir a necessidade de estoque distribuído geograficamente.

**Comment by miguelurtado** [comment]
Muito bom, vim aqui justamente atrás de Cep de Origem - Variável.
Parabéns pelo Plugin!

**Comment by webmastertesco** [comment]
Pessoal, coloquei uma interação em #9. Demora para responderem????? Obrigado.

**Comment by webmastertesco** [comment]
Preciso colocar as seguintes opcoes na Classe de Entrega do Impresso:
Qualquer classe de entrega
Nenhuma classe de entrega
Hoje sou obrigado a inserir alguma classe, mas preciso modificar isso. Se alguém puder ajudar, agradeço. Abcs
