### ISSUE TITLE
Aviso por SMS

### ISSUE THREAD

**Issue by claudiosanches** [claudiosanches/woocommerce-correios#58]
Apenas para clientes que tem contrato com os Correios: https://www.correios.com.br/para-voce/correios-de-a-a-z/entrega-interativa#tab-1

NOTA: Não vou conseguir desenvolver isso se eu não conseguir encontrar alguém que tem contrato com os Correios para me informar os dados para testar.

**Comment by caci** [comment]
Será que tem como usar os dados do UOL PagSeguro para testes?
Código administrativo: 12515221
Senha administrativa:  01109184

**Comment by claudiosmweb** [comment]
Não vou usar dados que não é bem de ninguém.
Ou alguém consegue esses dados com o CPNJ da própria empresa cadastrado lá ou eu não faço isso.
Não tem "tapa" buraco.

**Comment by felippe-wi3** [comment]
Claudio, 
Estava dando uma olhada na entrega interativa dos correios e, pelo que vi, parece que não é necessário ter contrato com os correios para utilizar o serviço.

**Quem pode cadastrar e receber notificações:**

Clientes com ou sem contrato, destinatários e/ou remetentes, cujos números dos celulares tenham sidos associados a um código de rastreamento de objeto.

https://www.correios.com.br/para-voce/correios-de-a-a-z/entrega-interativa#tab-1

**Comment by claudiosanches** [comment]
@felippe-wi3 por favor, olhe novamente a tabela de quem pode gerar isso pela API, no caso quem vai poder fazer isso por XML/Web antes de enviar o pedido não apenas na agencia dos Correios ao enviar.

**Comment by felippe-wi3** [comment]
Está certo!  Acabei não me atentando a isso.

Irei verificar uma conta que tenha contrato com eles para realizar teste.

Em 19 de dez de 2016 3:06 PM, "Claudio Sanches" <notifications@github.com>
escreveu:

**Comment by claudiosanches** [comment]
Fechando já que não tem ninguém para me emprestar as chaves da própria empresa para que eu consiga fazer testes.
