### ISSUE TITLE
Valor muito alto para frete internacional, dias para entrega ao contrário e possibilidade de tradução para Inglês

### ISSUE THREAD

**Issue by armaduarte** [claudiosanches/woocommerce-correios#63]
Olá desenvolvedores,

Estou usando esse plugin para um Woocommerce brasileiro mas que só vende para fora do Brasil, por esse motivo, os métodos de frete que eu utilizo são somente os internacionais dos correios.

Abaixo estou colocando duas imagens, uma da loja com o WooCommerce no checkout e na outra a tela dos correios para um frete para Japão, Okinawa.

![image](https://cloud.githubusercontent.com/assets/3899782/19698876/bbd4124c-9acf-11e6-9716-c049c6fbccb9.png)

![image](https://cloud.githubusercontent.com/assets/3899782/19699014/565acbda-9ad0-11e6-85b7-fde4eaaa70b8.png)

Primeiro problema é o valor muito alto no plugin.
Ele está calculando o valor corretamente, mas na hora de exibir na loja, como a moeda setada na loja é $ (USD), então ele coloca o frete na mesma moeda, então o frete fica inviável, pois este valor é o valor em R$ (BRL). Como posso fazer para que ele mostre o valor convertido para Dolar e não o valor de Reais com um $ na frete?

Segundo problema é a quantidade de dias do maior para o menor.
Ele está mostrando que o prazo de entrega, no plugin, é de 11 a 7 dias úteis e 22 a 18 dias úteis. Como faz para arrumar isso?

Terceira problema é saber como traduz para inglês.
Eu gostaria que o "dias úteis" fosse traduzido para Inglês "working days", como eu posso fazer issO?

**Comment by claudiosanches** [comment]
> Como posso fazer para que ele mostre o valor convertido para Dolar e não o valor de Reais com um $ na frete?

Fora do escopo deste plugin e você pode conveter isso usando o WooCommerce, sem necessidade de alterar nada neste plugin.

>Segundo problema é a quantidade de dias do maior para o menor.
>Ele está mostrando que o prazo de entrega, no plugin, é de 11 a 7 dias úteis e 22 a 18 dias úteis. >Como faz para arrumar isso?
>Terceira problema é saber como traduz para inglês.
>Eu gostaria que o "dias úteis" fosse traduzido para Inglês "working days", como eu posso fazer issO?

Os Correios que retorna esse texto, exatamente da forma que esta ai, se deseja mudar ele, também é possível fazer usando filtros no WooCommerce, sem ter que alterar qualquer coisa neste plugin.

**Comment by armaduarte** [comment]
Pode me dizer como eu faço para converter isso usando o WooCommerce?

**Comment by claudiosanches** [comment]
Como eu falei, não faz parte do escopo deste plugin, se quer fazer perguntas sobre o WooCommerce é melhor buscar um fórum de suporte do WooCommerce ou até mesmo no https://br.wordpress.org/support/
Se tiver qualquer pergunta ou problema especifico com este plugin, vou ficar feliz em responder, entretanto fica impossível ajudar com questões fora do plugin aqui. Se perguntar no fórum de suporte brasileiro eu respondo quando chegar no seu tópico, estou quase sempre por lá responder o que esta na tag `woocommerce`.

**Comment by armaduarte** [comment]
Certo, então eu tenho uma pergunta específica desse plugin:

Como eu faço para que o frete seja mostrado no valor condizente à cotação do da moeda que a loja inteira está setada? Porque se eu chegar no WooCommerce e perguntar isso vão me falar "Fale com o desenvolvedor do plugin, porque esse valor é o plugin quem tem que dar", o que eu não tiro a razão.

Por isso é que estou perguntando específicamente para o desenvolvedor do plugin.

**Comment by claudiosanches** [comment]
@armaduarte sobre a última coisa que você falou e deletou, eu ainda não estou encontrando o tópico no https://br.wordpress.org/support/ sobre isso para poder responder lá como fazer com o WooCommerce.

**Comment by armaduarte** [comment]
@claudiosanches eu deletei porque eu consegui resolver o problema. Modifiquei o arquivo includes/abstract/abstract-wc-correios-shipping-international.php e consegui fazer as modificações.

Só não sei como commitar ou enviar o arquivo para cá. Mas se quiser, eu posso colar o código aqui do arquivo.

**Comment by claudiosanches** [comment]
Modificar esse arquivo prejudica você mesmo, tornando impossível atualizar o plugin.
E como eu falei, da para fazer isso com o WooCommerce sem nem tocar no código desse plugin.
