### ISSUE TITLE
Possibilidade de filtrar o CEP de origem pelos dados do pacote

### ISSUE THREAD

**Issue by luizbills** [claudiosanches/woocommerce-correios#64]
Estou desenvolvendo um marketplace e nele eu divido o carrinho em vários pacotes separando os produtos por vendedor. Para continuar usando correios como método de correios e deixar que cada vendedor use seu próprio CEP de origem, estou pensando em alterar o filtro [`woocommerce_correios_origin_postcode`](https://github.com/claudiosanches/woocommerce-correios/blob/master/includes/class-wc-correios-webservice.php#L401) para que eu possa ter acesso a informações dos produtos (no meu caso o vendedor) do pacote que está sendo calculado naquele momento. Posso estar enviando um PR depois com minha solução?

**Comment by claudiosanches** [comment]
Sim claro, mas o WooCommerce já permite mais de um pacote por pedido, esta usando isso né?

**Comment by claudiosanches** [comment]
@luizbills você não respondeu minha pergunta ainda.

**Comment by luizbills** [comment]
@claudiosanches foi mal, esqueci kkk
Sim, estou separado o carrinhos em vários pacotes pelo core do woocommerce mesmo. Ai com a informação do pacote no filtro posso mudar o CEP configurado para o do vendedor dono do produto.

**Comment by claudiosanches** [comment]
@luizbills só garantindo que você testou isso :P

**Comment by claudiosanches** [comment]
@luizbills acabei de dar merge, até segunda vou lançar uma versão nova, porque acho que vou aproveitar e dar suporte para adicionar classes de entrega, o que facilita também para marketplace ou quem vende produtos que saiem de locais diferentes.
Obrigado velho.
