### ISSUE TITLE
Email é envio sem o rastreio

### ISSUE THREAD

**Issue by MarceloCPires** [claudiosanches/woocommerce-correios#66]
Ola 
Tudo esta funcionando muito bem com o plugin o unico problema é que quando coloco o numero de rastreio o e-mail enviado não apresenta o numero.
O mesmo email carrega o numero do pedido mas não o rastreio.

Obrigado pelo auxilio

Marcelo

**Comment by claudiosanches** [comment]
E-mail é enviado apenas na hora que salva o código de rastreio.
