### ISSUE TITLE
Erro Correios

### ISSUE THREAD

**Issue by matheusgsa** [claudiosanches/woocommerce-correios#68]
Boa Tarde Claudio,

O Plugin do Correio Woocommerce esta com um erro. Poderia me ajudar? @claudiosanches [http://lojatrevidamodas.com.br/wp-content/uploads/2016/12/Error.png](url)

**Comment by claudiosanches** [comment]
Não tem nenhum erro no screenshot que você esta mostrando.

**Comment by matheusgsa** [comment]
As letras todas exprimidas juntos dos botões

**Comment by claudiosanches** [comment]
@matheusgsa mas quem mostra as opções de regre com essas "letras todas exprimidas juntos dos botões" não é o plugin dos Correios.
