### ISSUE TITLE
Frete sedex não aparece no cálculo do carrinho

### ISSUE THREAD

**Issue by epdsantos** [claudiosanches/woocommerce-correios#69]
Após inserir o CEP, aparece somente o valor do frete via PAC. O sedex não aparece.
O frete via sedex está habilitado e configurado.
Versão do wordpress 4.7.

**Comment by epdsantos** [comment]
Corrigindo a informação. Só calcula sedex para produtos acima de R$ 15,00.

**Comment by claudiosanches** [comment]
Sim, sedex não permite seguro para valores com menos do que 15 reais.
