### ISSUE TITLE
Cadastro do código de rastreamento

### ISSUE THREAD

**Issue by Fdmoscardini** [claudiosanches/woocommerce-correios#72]
Boa noite!

Ao cadastrar o código de rastreamento é criado apenas uma nota no painel e enviado o e-mail, mas o código não fica salvo no campo de cadastrado e nem mesmo é possível exibir a tabela de histórico na página Minha Conta.

A versão do meu PHP é a 7.0.16

Vocês sabem se existe alguma incompatibilidade nesta versão do PHP?

Obrigado!

**Comment by Fdmoscardini** [comment]
Esqueci de informar que o plugin no meu site já está na versão 3.2.1

**Comment by claudiosanches** [comment]
Acabei de corrigir em https://github.com/claudiosanches/woocommerce-correios/commit/f555ed02d7ce95356d46219d1908e7d8791b5307
Basta atualizar para versão 3.2.2 que vai estar funcionando agora.
Obrigado.
