### ISSUE TITLE
Validação do cep

### ISSUE THREAD

**Issue by Fdmoscardini** [claudiosanches/woocommerce-correios#73]
Boa tarde,

Vocês podem me informar se na requisição do cálculo do frete é realizado a validação do CEP? Por exemplo, quando eu digito 12345-678 ele retorno um valor de frete, mas ao consultar o CEP no sistema do Correios é retornado 'DADOS NAO ENCONTRADOS'

Aconteceu de um cliente digitar um CEP que não existe e finalizou o pedido com o valor.

Neste caso como é realizado o processo? 

Obrigado!

**Comment by claudiosanches** [comment]
Não tem nenhuma validação, até porque quem faz isso é os Correios.
Se enviar um CEP inválido para o Webservice dos Correios, não vai retornar nenhuma informação de frete e ainda dizer que o CEP é inválido, o mesmo é retornado pelo plugin.

**Comment by Fdmoscardini** [comment]
Estranho, quando realizo o teste com o CEP 12345-678 no plugin retorna um valor de frete e no sistema do correios como 'DADOS NAO ENCONTRADOS'. Pra você é retornado assim também ?

**Comment by claudiosanches** [comment]
Basta ver o log do plugin, no caso para PAC Sedex e outros métodos, tudo é pelo Webservice dos Correios.
Se o Webservice dos Correios esta valendo que esta valido, é porque para os Correios esta valido.

**Comment by claudiosanches** [comment]
Aqui um teste com o CEP que você falou como destino: http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?nCdServico=41106&nCdEmpresa&sDsSenha&sCepDestino=12345678&sCepOrigem=01311300&nVlAltura=2&nVlLargura=11&nVlDiametro=0&nVlComprimento=16&nVlPeso=0&nCdFormato=1&sCdMaoPropria=N&nVlValorDeclarado=10&sCdAvisoRecebimento=N&StrRetorno=xml

**Comment by maroAlmeida** [comment]
Por gentileza, preciso de ajuda para configurar região de entrega.
 Criei uma região extra, São Paulo, coloquei o método de entrega, e coloco o cep na lista "Limitar para CEPs específicos", e esses cep's da lista, qdo vamos realizar a compra, ele não realiza o método de entrega selecionado.

Como posso resolver?
Obrigada.

**Comment by claudiosanches** [comment]
@maroAlmeida no caso configurando as áreas de entrega do WooCommerce e não deste plugin.
Melhor usar um fórum sobre WooCommerce ou o fórum de suporte brasileiro do WordPress: https://br.wordpress.org/support/forum/plugins-e-codigos/
