### ISSUE TITLE
Formato de Rolo / Prisma

### ISSUE THREAD

**Issue by abensur** [claudiosanches/woocommerce-correios#74]
É possível usar esse tipo de formato?

<img width="346" alt="screen shot 2017-04-03 at 11 20 30 pm" src="https://cloud.githubusercontent.com/assets/2366216/24639051/71bb99b0-18c3-11e7-859c-f472523be2f3.png">

**Comment by claudiosanches** [comment]
Por padrão o que vai dar diferença de valor é o peso e assim boa parte do tempo contando como um pacote vai ficar tudo ok.
Mas ainda assim você pode criar o seu próprio calculo com os dados do pacote e substituir os gerados pelo plugin usando o filtro `woocommerce_correios_shipping_args`.
