### ISSUE TITLE
Novos códigos PAC/Sedex ( Contrato Agência )

### ISSUE THREAD

**Issue by danilowm** [claudiosanches/woocommerce-correios#75]
Claudio, tudo bem? Está sabendo algo sobre essa nova tabela de códigos enviado pelos Correios

"Informamos que hoje 06/04 entra em vigor a nova tabela de encomendas e os objetos deverão ser postados com os novos códigos:
Tabela encomenda 4.1 – E-commerce 1

PAC – 04669 – PAC Contrato Agência
SEDEX – 04162 – Sedex Contrato Agência"

**Comment by claudiosanches** [comment]
Ambos são para quem tem contrato e nem todos os contratos usam os mesmos códigos.
No caso se você tem contrato com os Correios e recebeu esse e-mail vai então precisar alterar, mas pode alterar isso na configuração do método de entrega, todos os métodos tem opções para trocar os códigos da forma que for necessário para você.
