### ISSUE TITLE
O plugin não está funcionando em https

### ISSUE THREAD

**Issue by fagworio** [claudiosanches/woocommerce-correios#77]
Coloquei https no meu domínio e o plugin parou de funcionar, Desinstalei e instalei todos os plugins que uso, inclusive o tema, mas ele não funciona.

Mas quando eu desativo o https do site ele volta a funcionar.

Existe alguma configuração extra que precisa ser feita, para que ele funcione em https?
---------
Resolvi o problema forçando o Woocommerce em https, não sei se é a melhor solução, mas funcionou.
Pode fechar a issue e desculpe pelo inconveniente..

**Comment by claudiosanches** [comment]
Funciona sem nenhum problema com HTTPS, ainda mais que não tem nada que HTTPS poderia influenciar no funcionamento deste plugin.
Problema deve estar vindo de outro lugar.
