### ISSUE TITLE
Tempo Adicional da entrega por Classe de Entrega e/ou Produto

### ISSUE THREAD

**Issue by mariovalney** [claudiosanches/woocommerce-correios#79]
Um tópico no Fórum de Suporte ( [Dias adicionais por produto](https://br.wordpress.org/support/topic/dias-adicionais-por-produto/) ) fez-me pensar se não seria interessante permitir que cada Classe de Entrega tenha a possibilidade de cadastrar um valor de "Tempo Adicional".

Outra abordagem seria esse Tempo Adicional ser cadastrado no produto, assim o usuário teria um controle maior e permitiria que houvessem produtos "Sob Demanda".

O que acha? Será que é algo trivial e útil?

P.S.: Para a primeira abordagem, acabei [criando um plugin](https://github.com/mariovalney/woocommerce-correios-adbsc) que poderíamos aproveitar (para a segunda abordagem, cadastrar isso via metadado no produto é ainda mais fácil).

**Comment by claudiosanches** [comment]
Esse tempo de entrega é uma previsão para os Correios, não algo que seja totalmente restrito, se tem coisas que mudam muito o tempo para ser entregue, tem várias formas de melhorar isso, inclusive desativando a opção no plugin e colocando na descrição do plugin o quanto tempo vai levar.

Além que no plugin já tem o filtro `woocommerce_correios_shipping_additional_time` para permitir mudar isso com base no que tem que produtos no pacote que precisa ser entregue, assim já permite personalização, então não vejo motivo de incluir mais uma opção no plugin.
