### ISSUE TITLE
Alteração código de serviço Correios

### ISSUE THREAD

**Issue by ricardobrg** [claudiosanches/woocommerce-correios#80]
O código de serviço padrão do sedex foi alterado hoje pra 04014. Quem usa o sedex com código padrão fica sem nenhuma clase de entrega no carrinho e recebe a mensagem no log

    [cServico] => SimpleXMLElement Object
        (
            [Codigo] => 40010
            [Valor] => 0
            [PrazoEntrega] => 0
            [ValorMaoPropria] => 0
            [ValorAvisoRecebimento] => 0
            [ValorValorDeclarado] => 0
            [ValorSemAdicionais] => 0
            [EntregaDomiciliar] => SimpleXMLElement Object
                (
                )

            [EntregaSabado] => SimpleXMLElement Object
                (
                )

            [Erro] => 001
            [MsgErro] => Codigo de servico invalido. Desde 05/05/2017 ele foi substituido pelo 04014.
        )

Pra consertar é só atualizar na página de configuração da área de entrega.

Não vi os outros códigos, pq to no cel, mas vou dar uma olhada mais tarde.

**Comment by ramon-villain** [comment]
O código do PAC também mudou, passou a ser "04510". Infelizmente não achei nenhuma informativa dos correios com a mudança dos códigos, para checarmos todos os novos números.

**Comment by ricardobrg** [comment]
Testei aqui no webservice direto e os códigos são esses:

04510 - PAC sem contrato
04669 - PAC com contrato
04014 - SEDEX sem contrato
04162 - SEDEX com contrato

Os outros estão dando serviço temporariamente disponível por causa da greve ou pq o serviço foi encerrado, como o e-sedex por exemplo...

Criei um tópico no fórum do plugin: https://wordpress.org/support/topic/solucao-nao-existe-nenhum-metodo-de-entrega-disponivel/

**Comment by claudiosanches** [comment]
Fechado em favor de #81
