### ISSUE TITLE
Problema com o css do código de rastreio no corpo do email.

### ISSUE THREAD

**Issue by FelixCoutinho** [claudiosanches/woocommerce-correios#83]
WooCommerce Versão 4.8
WooCommerce Correios Versão 3.4.1
GMail e Expresso (Não testei outros)

Existe um problema que impede a visualização do código de rastreio dentro do email. O texto/link parece estar usando a mesma cor do fundo. Não houve alteração do template padrão.

Seguem imagens:

![screenshot-mail google com-2017-06-09-15-07-11](https://user-images.githubusercontent.com/840285/26988535-3c7d4fae-4d26-11e7-9a98-789d2c7ade4d.png)
![screenshot-correiov3 dataprev gov br-2017-06-09-15-06-48](https://user-images.githubusercontent.com/840285/26988537-3c828672-4d26-11e7-9f6c-6baa9cdb11db.png)
![screenshot-mail google com-2017-06-09-15-11-35](https://user-images.githubusercontent.com/840285/26988536-3c813948-4d26-11e7-91bd-a37bdb244007.png)

**Comment by claudiosanches** [comment]
Não é configurada qualquer cor para o link, se tem algum CSS é na sua configuração de template de e-mail do WooCommerce ou no seu tema.
