### ISSUE TITLE
Não calcula PAC para encomendas abaixo de R$18

### ISSUE THREAD

**Issue by Chicodarave** [claudiosanches/woocommerce-correios#85]
Prezado Claudio, acho que encontrei um pequeno bug, mas creio ser "cagada" dos Correios.

Não está calculando frete PAC corporativo para encomendas com valor inferior a R$18,00.
Creio que não seja problema corrigir, só modificar o código para manter o valor mínimo em R$18,00 caso seja menos.
Segue log abaixo.

Nice plugin BTW.

PS: PAC e Sedex corporativo também não estão calculando, porém quando a entrega é na mesma localidade, mas esse a culpa é inteira dos Correios e não vejo jeito de corrigir no módulo. (erro -888)

08-03-2017 @ 01:39:35 - Requesting Correios WebServices: http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?nCdServico=04510&nCdEmpresa&sDsSenha&sCepDestino=45998229&sCepOrigem=88102971&nVlAltura=4&nVlLargura=11&nVlDiametro=0&nVlComprimento=16&nVlPeso=0,018&nCdFormato=1&sCdMaoPropria=N&nVlValorDeclarado=9&sCdAvisoRecebimento=N&StrRetorno=xml
08-03-2017 @ 01:39:36 - Correios WebServices response: SimpleXMLElement Object
(
    [cServico] => SimpleXMLElement Object
        (
            [Codigo] => 04510
            [Valor] => 0,00
            [PrazoEntrega] => 0
            [ValorSemAdicionais] => 0,00
            [ValorMaoPropria] => 0,00
            [ValorAvisoRecebimento] => 0,00
            [ValorValorDeclarado] => 0,00
            [EntregaDomiciliar] => SimpleXMLElement Object
                (
                )

            [EntregaSabado] => SimpleXMLElement Object
                (
                )

            [Erro] => -5
            [MsgErro] => O Valor Declarado nao deve ser menor que R$ 18,00.
        )

)

**Comment by Chicodarave** [comment]
Prezado, este problema voltou, tanto para PAC quanto para Sedex

**Comment by claudiosanches** [comment]
@Chicodarave em qual método?

**Comment by Chicodarave** [comment]
Prezado, eu não cheguei a fazer testes a fundo, mas aconteceu assim:
Cliente me chamou reclamando que não conseguia realizar o pedido, dava mensagem que não haviam formas de envio para a região dela.
Conferi CEP ok
Fiz um pedido teste ok
Dai pedi pra ela me mandar a lista dos itens, fiz um pedido igual e apresentou o mesmo erro.
No log do PAC apareceu: "[MsgErro] => O Valor Declarado nao deve ser menor que R$ 18,00."
Dai eu fiz a mesma gambiarra que tinha feito na vez passada, antes de você corrigir:
Em: woocommerce-correios/includes/class-wc-correios-webservice.php

`
	/**
	 * Set declared value.
	 *
	 * @param string $declared_value Declared value.
	 */
	public function set_declared_value( $declared_value = '0' ) {
		//$this->declared_value = $declared_value;
		$this->declared_value = ($declared_value<18) ? 20 : $declared_value;`

Dai voltou tudo a funcionar, apareceu PAC e Sedex (?)
Se precisar faço testes mais a fundo, não fiz pois teria que colocar uma cópia do sistema em local (tenho medo de mexer no que está online)

**Comment by Chicodarave** [comment]
Prezado, eu não cheguei a fazer testes a fundo, mas aconteceu assim:
Cliente me chamou reclamando que não conseguia realizar o pedido, dava mensagem que não haviam formas de envio para a região dela.
Conferi CEP ok
Fiz um pedido teste ok
Dai pedi pra ela me mandar a lista dos itens, fiz um pedido igual e apresentou o mesmo erro.
No log do PAC apareceu: "[MsgErro] => O Valor Declarado nao deve ser menor que R$ 18,00."
Dai eu fiz a mesma gambiarra que tinha feito na vez passada, antes de você corrigir:
Em: woocommerce-correios/includes/class-wc-correios-webservice.php

	/**
	 * Set declared value.
	 *
	 * @param string $declared_value Declared value.
	 */
	public function set_declared_value( $declared_value = '0' ) {
		//$this->declared_value = $declared_value;
		$this->declared_value = ($declared_value<18) ? 20 : $declared_value;
	}

Dai voltou tudo a funcionar, apareceu PAC e Sedex (?)
Se precisar faço testes mais a fundo, não fiz pois teria que colocar uma cópia do sistema em local (tenho medo de mexer no que está online)

**Comment by claudiosanches** [comment]
Mas no PAC já esta fazendo isso.

**Comment by claudiosanches** [comment]
Acabei de testar e funciona sem nenhum problema.
Qual é o valor dos produtos no carrinho?

**Comment by Chicodarave** [comment]
Era em torno de R$13,00
Posé, eu também estranhei pois já tinha visto a correção, mas o problema realmente aconteceu e o módulo estava atualizado.

**Comment by claudiosanches** [comment]
Acabei de testar com 13 reais e esta funcionando sem nenhum problema.
Usando ele atualizado?

**Comment by Chicodarave** [comment]
Sim, estava atualizado na data (dia 24), lembro de ter olhado.
Vou te mandar o log para não haver dúvida:

10-24-2017 @ 02:02:59 - Requesting Correios WebServices: http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?nCdServico=04669&nCdEmpresa=17226961&sDsSenha=11683882&sCepDestino=89218691&sCepOrigem=88102971&nVlAltura=8&nVlLargura=11&nVlDiametro=0&nVlComprimento=16&nVlPeso=0,069&nCdFormato=1&sCdMaoPropria=N&nVlValorDeclarado=17&sCdAvisoRecebimento=N&StrRetorno=xml
10-24-2017 @ 02:02:59 - Correios WebServices response: SimpleXMLElement Object
(
    [cServico] => SimpleXMLElement Object
        (
            [Codigo] => 04669
            [Valor] => 0,00
            [PrazoEntrega] => 0
            [ValorSemAdicionais] => 0,00
            [ValorMaoPropria] => 0,00
            [ValorAvisoRecebimento] => 0,00
            [ValorValorDeclarado] => 0,00
            [EntregaDomiciliar] => SimpleXMLElement Object
                (
                )

            [EntregaSabado] => SimpleXMLElement Object
                (
                )

            [Erro] => -5
            [MsgErro] => O Valor Declarado nao deve ser menor que R$ 18,00.
            [obsFim] => SimpleXMLElement Object
                (
                )

        )

)


==========Sedex============
10-24-2017 @ 02:02:59 - Requesting Correios WebServices: http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?nCdServico=04162&nCdEmpresa=17226961&sDsSenha=11683882&sCepDestino=89218691&sCepOrigem=88102971&nVlAltura=8&nVlLargura=11&nVlDiametro=0&nVlComprimento=16&nVlPeso=0,069&nCdFormato=1&sCdMaoPropria=N&nVlValorDeclarado=17&sCdAvisoRecebimento=N&StrRetorno=xml
10-24-2017 @ 02:03:00 - Correios WebServices response: SimpleXMLElement Object
(
    [cServico] => SimpleXMLElement Object
        (
            [Codigo] => 04162
            [Valor] => 0,00
            [PrazoEntrega] => 0
            [ValorSemAdicionais] => 0,00
            [ValorMaoPropria] => 0,00
            [ValorAvisoRecebimento] => 0,00
            [ValorValorDeclarado] => 0,00
            [EntregaDomiciliar] => SimpleXMLElement Object
                (
                )

            [EntregaSabado] => SimpleXMLElement Object
                (
                )

            [Erro] => -5
            [MsgErro] => O Valor Declarado nao deve ser menor que R$ 18,00.
            [obsFim] => SimpleXMLElement Object
                (
                )

        )

)

**Comment by claudiosanches** [comment]
Na verdade calculando apenas a baixo de 16.

**Comment by Chicodarave** [comment]
Logo após a atualização:
(Sedex)

10-27-2017 @ 13:17:58 - Requesting Correios WebServices: http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?nCdServico=04162&nCdEmpresa=REMOVIDO&sDsSenha=REMOVIDO&sCepDestino=89218691&sCepOrigem=88102971&nVlAltura=8&nVlLargura=11&nVlDiametro=0&nVlComprimento=16&nVlPeso=0,119&nCdFormato=1&sCdMaoPropria=N&nVlValorDeclarado=17&sCdAvisoRecebimento=N&StrRetorno=xml
10-27-2017 @ 13:17:58 - Correios WebServices response: SimpleXMLElement Object
(
    [cServico] => SimpleXMLElement Object
        (
            [Codigo] => 04162
            [Valor] => 0,00
            [PrazoEntrega] => 0
            [ValorSemAdicionais] => 0,00
            [ValorMaoPropria] => 0,00
            [ValorAvisoRecebimento] => 0,00
            [ValorValorDeclarado] => 0,00
            [EntregaDomiciliar] => SimpleXMLElement Object
                (
                )

            [EntregaSabado] => SimpleXMLElement Object
                (
                )

            [Erro] => -5
            [MsgErro] => O Valor Declarado nao deve ser menor que R$ 18,00.
            [obsFim] => SimpleXMLElement Object
                (
                )

        )

)

**Comment by claudiosanches** [comment]
Atualização de ontem?

**Comment by claudiosanches** [comment]
Mas eu só alterei isso para PAC.
Sabendo agora que mudou para Sedex e Sedex10 também

**Comment by Chicodarave** [comment]
Desculpe Claudio, eu não tenho muito entendimento nessa área, e não tive tempo para testar a fundo, estou tentando ajudar como posso.
Hoje fiz alguns testes, algo acontece com o Sedex e o Sedex10 também, mas parece que é dentro de alguma faixa de preço específica, não consegui determinar a faixa EXATA mas ficou assim:
valor do pedido: 16,49<ERRO<17,99
Tanto para Sedex quanto para Sedex10 não calcula e dá erro -5 no log:
[Erro] => -5
[MsgErro] => O Valor Declarado nao deve ser menor que R$ 18,00.

**Comment by claudiosanches** [comment]
Mas apenas quando tem contrato ou sem?

**Comment by Chicodarave** [comment]
Só testei com contrato.

**Comment by monacchesi** [comment]
Prezado Claudio, creio que este problema voltou a acontecer.

**Comment by monacchesi** [comment]
Olá Claudio, tudo bem grande?!

Eu detectei um possível problema que pode estar co-relacionado com este issue e pode valer um pouco de sua atenção. 

Tenho 4 websites desenvolvido em WC que utiliza o seu plugin, qualquer produto com valor quebrado dentro de R$ 18, ou seja R$ 18,01 a 18,99 está gerando falha no plugin durante o calculo do frete. Aparece somente 'retirada na loja'. 

Grande abraço.

**Comment by claudiosanches** [comment]
@monacchesi usando a última versão? Porque eu corrigi esse problema tem algum tempo.

**Comment by plovinicius** [comment]
Problema ainda continua para mim, caso tento usar algum valor abaixo do mínimo requerido pelos Correios ele retorna erro, não deveria enviar sempre o valor mínimo requerido pela API dos Correios para o calculo ?
Dessa forma nunca iria dar erro de valor mínimo abaixo do esperado ou algo do tipo.
