### ISSUE TITLE
Sugestão: Peso do pacote

### ISSUE THREAD

**Issue by Chicodarave** [claudiosanches/woocommerce-correios#86]
Saudações.
Eu não sei se aqui é o melhor lugar para dar sugestões, mas segue:

Seria legal se o módulo fizesse um calculo do peso do pacote para incrementar junto com o peso do pedido e assim calcular um valor mais adequado.
Eu tive algumas ideias:
1. Um campo para inserir um peso fixo ao peso total.
2. Adicionar uma porcentagem do peso total ao peso total (ex: peso total + 5%)
3. Adicionar uma porcentagem do volume total ao peso total.
4. Uma tabela onde pudesse ser adicionadas as embalagens, o volume máximo de cada uma e o peso, o sistema usaria o volume do pedido para escolher a mais adequada e adicionaria o peso dela ao peso total.

Pelo meu conhecimento intermediário eu acho que coloquei da forma mais simples a forma mais complexa.
Também acho que nenhuma das opções vai resolver o problema 100% mas com certeza vai ajudar bastante.
Minha opção preferida é a 3.

Espero que minha sugestão ajude em algo.
Ficaria muito animado de ver minha sugestão implementada no módulo.
Um abraço.

**Comment by claudiosanches** [comment]
Bom, o que da para fazer é adicionar uma opção nova para adicionar peso extra.

**Comment by Chicodarave** [comment]
Boa Claudio! Tu é foda!
Obrigado!
