### ISSUE TITLE
Não calcula frete em áreas de risco

### ISSUE THREAD

**Issue by leonardoalmeida** [claudiosanches/woocommerce-correios#88]
Quando há uma consulta de CEP em áreas de risco, ao invés de somente mostrar um tempo de entrega maior, mostra que não há método de entrega disponível, sendo que se usar outro CEP normal (sem restrição), calcula normalmente.

Segue log:
09-13-2017 @ 10:06:25 – Correios WebServices response: SimpleXMLElement Object
(
[cServico] => SimpleXMLElement Object
(
[Codigo] => 04014
[Valor] => 17,20
[PrazoEntrega] => 8
[ValorSemAdicionais] => 17,20
[ValorMaoPropria] => 0,00
[ValorAvisoRecebimento] => 0,00
[ValorValorDeclarado] => 0,00
[EntregaDomiciliar] => S
[EntregaSabado] => S
[Erro] => 011
[MsgErro] => O CEP de destino está sujeito a condições especiais de entrega pela ECT e será realizada com o acréscimo de até 7 (sete) dias úteis ao prazo regular.
)

**Comment by ChicaoCoelho** [comment]
Fiz os testes na minha instalação e também deu o mesmo erro, utilizando a versão versão 3.4.1

**Comment by ChicaoCoelho** [comment]
Resolvi com um workaround que o Valdeir Santos publicou no grupo:

> Valdeir Santos Acesse o plugin, vá até o diretório "abstracts". Abra o aquivo abstract-wc-correios-shipping.php. Procure pelo método "get_accepted_error_codes();" No arrays com os códigos, adicione o código deste erro, que é o "011". Salve e boas vendas.

**Comment by everaldomatias** [comment]
Pra mim estava aparecendo dois erros frequentemente, o 011 e o -888

[Erro] => -888
[MsgErro] => Erro ao calcular tarifa no SGPB. ERP-007: CEP de origem nao pode postar para o CEP de destino informado(-1).

**Comment by mayconjcm** [comment]
@ChicaoCoelho Deu certo aqui o workaround do Valdeir. o/

**Comment by henriquemattos** [comment]
O mesmo aconteceu comigo referente à um CEP de Campo Grande, zona norte do Rio de Janeiro. Logo depois com um CEP de Itaquaquecetuba, periferia de São Paulo.

Se o Correios entrega adicionando dias ao prazo e cobrando mais caro, ainda assim a entrega pode ser feita, basta calcular o prazo e custo em cima disso.

**Comment by 3dingbat** [comment]
Fiz um PR com essa correção
https://github.com/claudiosanches/woocommerce-correios/pull/89

**Comment by valdeirs2** [comment]
Pessoal, este workaround que deixei no grupo, resolve, mas não é uma boa prática. A melhor forma de corrigir este erro, é fazer a alteração no functions.php do tema, já que existe um filter no plugin para adicionar mais códigos de erro.

Segue o código para inserir no functions.php

`function add_new_accepted_error_code( $codes ){

    $codes[] = '011';
    
    return $codes;
}

add_filter('woocommerce_correios_accepted_error_codes','add_new_accepted_error_code', PHP_INT_MAX);`

**Comment by ricardobrg** [comment]
@valdeirs2 deu erro na formataçã aí... obrigado pelo código!

**Comment by claudiosanches** [comment]
Corrigido em #89

**Comment by Chicodarave** [comment]
Esbarrei nesse problema ontem de noite, uma cliente veio reclamar que não conseguia calcular o frete.

destino: 02649030

erro: "Não existe nenhum método de entrega disponível. Por favor, certifique-se de que o seu endereço está correto ou entre em contato conosco caso você precise de ajuda."


10-06-2017 @ 02:44:36 - Requesting Correios WebServices: http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?nCdServico=04669&nCdEmpresa=17226961&sDsSenha=11683882&sCepDestino=02649030&sCepOrigem=88102971&nVlAltura=5&nVlLargura=11&nVlDiametro=0&nVlComprimento=16&nVlPeso=0,065&nCdFormato=1&sCdMaoPropria=N&nVlValorDeclarado=20&sCdAvisoRecebimento=N&StrRetorno=xml
10-06-2017 @ 02:44:37 - Correios WebServices response: SimpleXMLElement Object
(
    [cServico] => SimpleXMLElement Object
        (
            [Codigo] => 04669
            [Valor] => 14,10
            [PrazoEntrega] => 14
            [ValorSemAdicionais] => 14,10
            [ValorMaoPropria] => 0,00
            [ValorAvisoRecebimento] => 0,00
            [ValorValorDeclarado] => 0,00
            [EntregaDomiciliar] => S
            [EntregaSabado] => N
            [Erro] => 011
            [MsgErro] => O CEP de destino está sujeito a condições especiais de entrega  pela  ECT e será realizada com o acréscimo de até 7 (sete) dias úteis ao prazo regular.
            [obsFim] => O CEP de destino está sujeito a condições especiais de entrega  pela  ECT e será realizada com o acréscimo de até 7 (sete) dias úteis ao prazo regular.
        )

)

10-06-2017 @ 02:44:44 - Weight and cubage of the order: Array
(
    [weight] => 0,065
    [height] => 5
    [width] => 11
    [length] => 16
)


Como faço para pegar a versão corrigida do módulo?
Obrigado.

**Comment by claudiosanches** [comment]
@Chicodarave esta corrigido já isso.

**Comment by Chicodarave** [comment]
@claudiosanches, então Claudio, eu vi pelas respostas que está resolvido, mas tive esse problema ontem... na verdade hoje de madrugada e até as 10:00 não tinha notificação de atualização pro módulo, dai ainda pouco fui olhar e tinha, atualizei, tentei de novo AGORA mas ainda está dando o mesmo erro...
Posso ter feito algo de errado?

Obrigado.

**Comment by claudiosanches** [comment]
@Chicodarave que mesmo erro? O que aparece no log?

**Comment by Chicodarave** [comment]
Tentei de novo agora e deu certo... vai entender...
Está perfeito! Obrigado Cláudio!
