### ISSUE TITLE
Mensagem

### ISSUE THREAD

**Issue by danubiapaiva** [claudiosanches/woocommerce-correios#90]
Claudio,

Mesmo marcando a opção "Forçar entrega para o endereço de cobrança do cliente.", esta solicitando que seja informado o endereço de entrega.
Exibe a mensagem:
"Por favor, informe um endereço para continuar."

Gostaria de usar somente o endereço de cobrança.

**Comment by claudiosanches** [comment]
Não estou entendendo isso.
O que você esta falando é parte do WooCommerce e não do WooCommerce Correios, não é algo que posso mudar neste plugin.
Se você esta buscando ajuda sobre o WooCommerce, seria melhor usar um canal de suporte para o WooCommerce.
