### ISSUE TITLE
FRETE GRÁTIS PARA 

### ISSUE THREAD

**Issue by n1l50n** [claudiosanches/woocommerce-correios#91]
Olá Claudio,

Gostaria de saber se é possível colocar frete grátis apenas para alguns produtos?

Grato
Nilson

**Comment by claudiosanches** [comment]
Bom, método de entrega grátis é do WooCommerce e não deste plugin, então basta configurar o frete do WooCommerce como você gostaria.
Se tiver perguntas especificas sobre os métodos de entrega deste plugin, eu vou ficar feliz em responder.
