### ISSUE TITLE
Porcentagem sobre o valor do frete.

### ISSUE THREAD

**Issue by Chicodarave** [claudiosanches/woocommerce-correios#92]
Saudações.

Costumo vender usando PagSeguro e PayPal, ambos cobram a taxa sobre o valor total do pedido (produtos + frete).
Várias vezes o valor do frete é próximo, igual ou até superior ao valor do pedido, e isso está me dando um custo extra.
Seria possível o módulo ter além de uma taxa fixa sobre o valor do frete ter também uma taxa de porcentagem? (para justamente compensar o custo do intermediador).

Obrigado.

**Comment by claudiosanches** [comment]
Tem a taxa de manuseio que você pode colocar um valor em porcentagem para ser adicionado ao valor total do frete.

**Comment by Chicodarave** [comment]
É que eu precisava adicionar +R$2 e + 5%
R$2,00 da embalagem.
5% da taxa.

**Comment by claudiosanches** [comment]
Então, pode usar o filtro `woocommerce_shipping_packages` do WooCommerce para alterar os valores.

**Comment by Chicodarave** [comment]
Vou ter que aprender a usar isso, mas agradeço a indicação da direção a ser tomada.
Um abraço.

**Comment by Chicodarave** [comment]
Cláudio, poderia fazer a gentileza de me dizer se esse código está ok e não causará problemas?
Muito obrigado.
(para adicionar 5% ao valor final do frete)

// Function
function chicodarave_woocommerce_package_rates( $rates, $package ) {
    foreach ( $rates as $rate_id => $rate ) {
        $current_cost = $rate->cost;
        $rates[ $rate_id ]->cost = $current_cost * 1.05;
    }
    
    return $rates;
}; 
         
// The hook
add_filter( 'woocommerce_package_rates', 'chicodarave_woocommerce_package_rates', 10, 2 );
