### ISSUE TITLE
Campo de estado não atualiza no checkout no Firefox ao recarregar a página.

### ISSUE THREAD

**Issue by CasperBraske** [claudiosanches/woocommerce-correios#94]
**Problema**

Depois de ter o endereço preenchido, ao recarregar a página de checkout no Firefox, o campo de estado não muda independente de o atributo "selected" estar presente.

**Solução**

Mudar as chamadas de `$().attr` para `$().prop` no arquivo autofill-address.js.

**Comment by claudiosanches** [comment]
Quem controla isso é o WooCommerce e não este plugin.

**Comment by claudiosanches** [comment]
Agora que vi que é com o autofill.
Vou verificar isso.

**Comment by claudiosanches** [comment]
Acabei de testar e funciona sem nenhum problema no firefox 57
